// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/service/backgroundservice_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i9;
import 'dart:ui' as _i15;

import 'package:flutter/material.dart' as _i18;
import 'package:geolocator/geolocator.dart' as _i17;
import 'package:http/http.dart' as _i7;
import 'package:latlong2/latlong.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:triplo/controller/servicecontroller.dart' as _i8;
import 'package:triplo/controller/trekking.dart' as _i10;
import 'package:triplo/l10n/app_localizations.dart' as _i14;
import 'package:triplo/model/trekking.dart' as _i11;
import 'package:triplo/service/authservice.dart' as _i2;
import 'package:triplo/service/geo.dart' as _i5;
import 'package:triplo/service/memory.dart' as _i3;
import 'package:triplo/service/notification.dart' as _i4;
import 'package:triplo/service/permission.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_1 extends _i1.SmartFake implements _i3.MemoryService {
  _FakeMemoryService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_2 extends _i1.SmartFake
    implements _i4.NotificationService {
  _FakeNotificationService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_3 extends _i1.SmartFake implements _i5.GeoService {
  _FakeGeoService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_4 extends _i1.SmartFake
    implements _i6.PermissionService {
  _FakePermissionService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_5 extends _i1.SmartFake implements _i7.Client {
  _FakeClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationLocationState_6 extends _i1.SmartFake
    implements _i8.NavigationLocationState {
  _FakeNavigationLocationState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_7 extends _i1.SmartFake implements _i9.File {
  _FakeFile_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i10.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_0(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i2.AuthService);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i4.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_2(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i4.NotificationService);

  @override
  List<_i11.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i11.Trekking>[],
          )
          as List<_i11.Trekking>);

  @override
  set authService(_i2.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set notification(_i4.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i11.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i11.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i11.Trekking?);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i12.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<List<_i11.Trekking>> searchTrekking(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrekking, [query]),
            returnValue: _i12.Future<List<_i11.Trekking>>.value(
              <_i11.Trekking>[],
            ),
          )
          as _i12.Future<List<_i11.Trekking>>);

  @override
  _i12.Future<_i11.Trekking?> fetchTrekkingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrekkingById, [id]),
            returnValue: _i12.Future<_i11.Trekking?>.value(),
          )
          as _i12.Future<_i11.Trekking?>);

  @override
  _i12.Future<List<_i11.Trekking>> getSavedTrekkings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedTrekkings, [uid]),
            returnValue: _i12.Future<List<_i11.Trekking>>.value(
              <_i11.Trekking>[],
            ),
          )
          as _i12.Future<List<_i11.Trekking>>);

  @override
  _i12.Future<void> addTrekkingToSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrekkingToSaved, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeTrekkingFromSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrekkingFromSaved, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isTrekkingSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrekkingSaved, [trekkingId]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i9.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i12.Future<_i9.File?>.value(),
          )
          as _i12.Future<_i9.File?>);

  @override
  _i12.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i14.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i9.File>> getCachedImages(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImages, [imagePaths]),
            returnValue: _i12.Future<List<_i9.File>>.value(<_i9.File>[]),
          )
          as _i12.Future<List<_i9.File>>);

  @override
  _i12.Future<_i11.Trekking?> getTrekkingByIdAsync(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [trekkingId]),
            returnValue: _i12.Future<_i11.Trekking?>.value(),
          )
          as _i12.Future<_i11.Trekking?>);

  @override
  _i12.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<_i11.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i12.Future<List<_i11.Trekking>>.value(
              <_i11.Trekking>[],
            ),
          )
          as _i12.Future<List<_i11.Trekking>>);

  @override
  _i12.Future<void> updateWeatherNotificationLastCheck() =>
      (super.noSuchMethod(
            Invocation.method(#updateWeatherNotificationLastCheck, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i8.ServiceController {
  MockServiceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i5.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_3(this, Invocation.getter(#geo)),
          )
          as _i5.GeoService);

  @override
  _i6.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_4(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i6.PermissionService);

  @override
  _i7.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_5(this, Invocation.getter(#client)),
          )
          as _i7.Client);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i5.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i6.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  String weatherTile(String? layer) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTile, [layer]),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
          )
          as String);

  @override
  String? resolveLayer(String? id) =>
      (super.noSuchMethod(Invocation.method(#resolveLayer, [id])) as String?);

  @override
  _i12.Future<_i16.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i12.Future<_i16.LatLng?>.value(),
          )
          as _i12.Future<_i16.LatLng?>);

  @override
  _i12.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang]),
            returnValue: _i12.Future<Map<String, dynamic>?>.value(),
          )
          as _i12.Future<Map<String, dynamic>?>);

  @override
  _i12.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang]),
            returnValue: _i12.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i12.Future<List<Map<String, dynamic>>?>);

  @override
  _i12.Future<bool> hasInternet([
    _i12.Future<List<_i9.InternetAddress>> Function(String)? lookup,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, [lookup]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = true}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i12.Future<List<Map<String, dynamic>>> mockAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, []),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon]),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<_i8.NavigationLocationState> loadNavigationLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadNavigationLocation, []),
            returnValue: _i12.Future<_i8.NavigationLocationState>.value(
              _FakeNavigationLocationState_6(
                this,
                Invocation.method(#loadNavigationLocation, []),
              ),
            ),
          )
          as _i12.Future<_i8.NavigationLocationState>);

  @override
  _i12.Stream<_i17.Position> navigationPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#navigationPositionStream, []),
            returnValue: _i12.Stream<_i17.Position>.empty(),
          )
          as _i12.Stream<_i17.Position>);

  @override
  _i12.Future<void> openGpsSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openGpsSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openPermissionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openPermissionSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  String googleSatelliteTile() =>
      (super.noSuchMethod(
            Invocation.method(#googleSatelliteTile, []),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
          )
          as String);

  @override
  String weatherTileFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTileFromId, [id]),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
          )
          as String);

  @override
  String legendTypeFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#legendTypeFromId, [id]),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
          )
          as String);

  @override
  _i12.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i12.Stream<double?>.empty(),
          )
          as _i12.Stream<double?>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setNavKey(_i18.GlobalKey<_i18.NavigatorState>? key) =>
      super.noSuchMethod(
        Invocation.method(#setNavKey, [key]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void handleNotificationTapForTest(String? payload) => super.noSuchMethod(
    Invocation.method(#handleNotificationTapForTest, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> showTrekkingNotification({
    required int? id,
    required String? title,
    required String? body,
    required String? payload,
    String? channelId = 'notifications_channel',
    String? channelName = 'Notifications',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showTrekkingNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
              #channelId: channelId,
              #channelName: channelName,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> showWeatherNotification({
    required int? id,
    required String? title,
    required String? body,
    String? payload = 'weather_alert',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showWeatherNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i3.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i9.File?> getImageFromDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromDisk, [url]),
            returnValue: _i12.Future<_i9.File?>.value(),
          )
          as _i12.Future<_i9.File?>);

  @override
  _i12.Future<_i9.File> cacheImageOnDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImageOnDisk, [url]),
            returnValue: _i12.Future<_i9.File>.value(
              _FakeFile_7(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
          )
          as _i12.Future<_i9.File>);

  @override
  _i12.Future<_i9.File?> getImageFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromMemory, [key]),
            returnValue: _i12.Future<_i9.File?>.value(),
          )
          as _i12.Future<_i9.File?>);

  @override
  void saveImageToMemory(String? key, _i9.File? file) => super.noSuchMethod(
    Invocation.method(#saveImageToMemory, [key, file]),
    returnValueForMissingStub: null,
  );

  @override
  void removeImageFromMemory(String? key) => super.noSuchMethod(
    Invocation.method(#removeImageFromMemory, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<String?> getSavedLocaleCode() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocaleCode, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> saveLocaleCode(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocaleCode, [localeCode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Set<String>> getShownWeatherAlertKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getShownWeatherAlertKeys, []),
            returnValue: _i12.Future<Set<String>>.value(<String>{}),
          )
          as _i12.Future<Set<String>>);

  @override
  _i12.Future<void> saveShownWeatherAlertKeys(Set<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#saveShownWeatherAlertKeys, [keys]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#addShownWeatherAlertKey, [key]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> hasShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasShownWeatherAlertKey, [key]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}
