// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/service/internetservice_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i10;

import 'package:geolocator/geolocator.dart' as _i11;
import 'package:http/http.dart' as _i5;
import 'package:latlong2/latlong.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:triplo/controller/servicecontroller.dart' as _i6;
import 'package:triplo/service/geo.dart' as _i3;
import 'package:triplo/service/memory.dart' as _i2;
import 'package:triplo/service/permission.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMemoryService_0 extends _i1.SmartFake implements _i2.MemoryService {
  _FakeMemoryService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_1 extends _i1.SmartFake implements _i3.GeoService {
  _FakeGeoService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_2 extends _i1.SmartFake
    implements _i4.PermissionService {
  _FakePermissionService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_3 extends _i1.SmartFake implements _i5.Client {
  _FakeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationLocationState_4 extends _i1.SmartFake
    implements _i6.NavigationLocationState {
  _FakeNavigationLocationState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i6.ServiceController {
  MockServiceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i2.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_0(this, Invocation.getter(#memory)),
          )
          as _i2.MemoryService);

  @override
  _i3.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_1(this, Invocation.getter(#geo)),
          )
          as _i3.GeoService);

  @override
  _i4.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_2(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i4.PermissionService);

  @override
  _i5.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_3(this, Invocation.getter(#client)),
          )
          as _i5.Client);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i2.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i3.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i4.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  String weatherTile(String? layer) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTile, [layer]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
          )
          as String);

  @override
  String? resolveLayer(String? id) =>
      (super.noSuchMethod(Invocation.method(#resolveLayer, [id])) as String?);

  @override
  _i8.Future<_i9.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i8.Future<_i9.LatLng?>.value(),
          )
          as _i8.Future<_i9.LatLng?>);

  @override
  _i8.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang]),
            returnValue: _i8.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i8.Future<List<Map<String, dynamic>>?>);

  @override
  _i8.Future<bool> hasInternet([
    _i8.Future<List<_i10.InternetAddress>> Function(String)? lookup,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, [lookup]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = true}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<List<Map<String, dynamic>>> mockAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<_i6.NavigationLocationState> loadNavigationLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadNavigationLocation, []),
            returnValue: _i8.Future<_i6.NavigationLocationState>.value(
              _FakeNavigationLocationState_4(
                this,
                Invocation.method(#loadNavigationLocation, []),
              ),
            ),
          )
          as _i8.Future<_i6.NavigationLocationState>);

  @override
  _i8.Stream<_i11.Position> navigationPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#navigationPositionStream, []),
            returnValue: _i8.Stream<_i11.Position>.empty(),
          )
          as _i8.Stream<_i11.Position>);

  @override
  _i8.Future<void> openGpsSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openGpsSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openPermissionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openPermissionSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String googleSatelliteTile() =>
      (super.noSuchMethod(
            Invocation.method(#googleSatelliteTile, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
          )
          as String);

  @override
  String weatherTileFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTileFromId, [id]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
          )
          as String);

  @override
  String legendTypeFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#legendTypeFromId, [id]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
          )
          as String);

  @override
  _i8.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i8.Stream<double?>.empty(),
          )
          as _i8.Stream<double?>);
}
