// Mocks generated by Mockito 5.4.6 from annotations
// in app_triplo_wearos/test/pages/GeoWatchPage/geowatchpage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i6;

import 'package:app_triplo_wearos/controller/language.dart' as _i13;
import 'package:app_triplo_wearos/controller/servicecontroller.dart' as _i14;
import 'package:app_triplo_wearos/controller/trekking.dart' as _i8;
import 'package:app_triplo_wearos/l10n/app_localizations.dart' as _i12;
import 'package:app_triplo_wearos/model/trekking.dart' as _i9;
import 'package:app_triplo_wearos/service/OSservice/geo.dart' as _i2;
import 'package:app_triplo_wearos/service/OSservice/memory.dart' as _i3;
import 'package:app_triplo_wearos/service/OSservice/notification.dart' as _i4;
import 'package:app_triplo_wearos/service/OSservice/permission_service.dart'
    as _i7;
import 'package:app_triplo_wearos/service/pairing_service.dart' as _i5;
import 'package:http/http.dart' as _i16;
import 'package:latlong2/latlong.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGeoService_0 extends _i1.SmartFake implements _i2.GeoService {
  _FakeGeoService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_1 extends _i1.SmartFake implements _i3.MemoryService {
  _FakeMemoryService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_2 extends _i1.SmartFake
    implements _i4.NotificationService {
  _FakeNotificationService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePairingService_3 extends _i1.SmartFake
    implements _i5.PairingService {
  _FakePairingService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_4 extends _i1.SmartFake implements _i6.Locale {
  _FakeLocale_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_5 extends _i1.SmartFake
    implements _i7.PermissionService {
  _FakePermissionService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i8.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_0(this, Invocation.getter(#geo)),
          )
          as _i2.GeoService);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i4.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_2(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i4.NotificationService);

  @override
  _i5.PairingService get pairingService =>
      (super.noSuchMethod(
            Invocation.getter(#pairingService),
            returnValue: _FakePairingService_3(
              this,
              Invocation.getter(#pairingService),
            ),
          )
          as _i5.PairingService);

  @override
  List<_i9.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i9.Trekking>[],
          )
          as List<_i9.Trekking>);

  @override
  set onTrekkingSelected(void Function(_i9.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i9.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i9.Trekking?);

  @override
  _i10.Future<_i9.Trekking?> getTrekkingByIdAsync(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [documentId]),
            returnValue: _i10.Future<_i9.Trekking?>.value(),
          )
          as _i10.Future<_i9.Trekking?>);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i10.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i10.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i12.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<_i9.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i10.Future<List<_i9.Trekking>>.value(
              <_i9.Trekking>[],
            ),
          )
          as _i10.Future<List<_i9.Trekking>>);

  @override
  _i10.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Language].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguage extends _i1.Mock implements _i13.Language {
  MockLanguage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_4(this, Invocation.getter(#locale)),
          )
          as _i6.Locale);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> setLocale(_i6.Locale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadSavedLocale() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedLocale, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i14.ServiceController {
  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
            returnValueForMissingStub: _FakeMemoryService_1(
              this,
              Invocation.getter(#memory),
            ),
          )
          as _i3.MemoryService);

  @override
  _i2.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_0(this, Invocation.getter(#geo)),
            returnValueForMissingStub: _FakeGeoService_0(
              this,
              Invocation.getter(#geo),
            ),
          )
          as _i2.GeoService);

  @override
  _i7.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_5(
              this,
              Invocation.getter(#permission),
            ),
            returnValueForMissingStub: _FakePermissionService_5(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i7.PermissionService);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i2.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i7.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i15.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i10.Future<_i15.LatLng?>.value(),
            returnValueForMissingStub: _i10.Future<_i15.LatLng?>.value(),
          )
          as _i10.Future<_i15.LatLng?>);

  @override
  _i10.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang, {
    _i16.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang], {#client: client}),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang, {
    _i16.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang], {#client: client}),
            returnValue: _i10.Future<List<Map<String, dynamic>>?>.value(),
            returnValueForMissingStub:
                _i10.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i10.Future<List<Map<String, dynamic>>?>);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = false}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  _i10.Future<bool> hasInternet() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<Map<String, dynamic>>> mockAlerts({_i16.Client? client}) =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, [], {#client: client}),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon, {
    _i16.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon], {#client: client}),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);
}
