// Mocks generated by Mockito 5.4.6 from annotations
// in app_triplo_wearos/test/service/OSservice/notification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:app_triplo_wearos/l10n/app_localizations.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i2.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get menu_title =>
      (super.noSuchMethod(
            Invocation.getter(#menu_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#menu_title),
            ),
          )
          as String);

  @override
  String get home_page_title =>
      (super.noSuchMethod(
            Invocation.getter(#home_page_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#home_page_title),
            ),
          )
          as String);

  @override
  String get repositioning_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#repositioning_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#repositioning_button_label),
            ),
          )
          as String);

  @override
  String get profile_page_title =>
      (super.noSuchMethod(
            Invocation.getter(#profile_page_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#profile_page_title),
            ),
          )
          as String);

  @override
  String get username_label =>
      (super.noSuchMethod(
            Invocation.getter(#username_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#username_label),
            ),
          )
          as String);

  @override
  String get password_label =>
      (super.noSuchMethod(
            Invocation.getter(#password_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#password_label),
            ),
          )
          as String);

  @override
  String get email_label =>
      (super.noSuchMethod(
            Invocation.getter(#email_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#email_label),
            ),
          )
          as String);

  @override
  String get totals_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#totals_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#totals_trekking_label),
            ),
          )
          as String);

  @override
  String get published_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#published_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#published_trekking_label),
            ),
          )
          as String);

  @override
  String get private_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#private_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#private_trekking_label),
            ),
          )
          as String);

  @override
  String get share_profile_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#share_profile_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#share_profile_button_label),
            ),
          )
          as String);

  @override
  String get watch_profile_dialog_level =>
      (super.noSuchMethod(
            Invocation.getter(#watch_profile_dialog_level),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#watch_profile_dialog_level),
            ),
          )
          as String);

  @override
  String get my_profile_dialog_level =>
      (super.noSuchMethod(
            Invocation.getter(#my_profile_dialog_level),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#my_profile_dialog_level),
            ),
          )
          as String);

  @override
  String get level_label =>
      (super.noSuchMethod(
            Invocation.getter(#level_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#level_label),
            ),
          )
          as String);

  @override
  String get beginner_level =>
      (super.noSuchMethod(
            Invocation.getter(#beginner_level),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#beginner_level),
            ),
          )
          as String);

  @override
  String get intermediate_level =>
      (super.noSuchMethod(
            Invocation.getter(#intermediate_level),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#intermediate_level),
            ),
          )
          as String);

  @override
  String get advanced_level =>
      (super.noSuchMethod(
            Invocation.getter(#advanced_level),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#advanced_level),
            ),
          )
          as String);

  @override
  String get no_public_diary_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_public_diary_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_public_diary_label),
            ),
          )
          as String);

  @override
  String get no_private_diary_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_private_diary_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_private_diary_label),
            ),
          )
          as String);

  @override
  String get no_saved_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_saved_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_saved_trekking_label),
            ),
          )
          as String);

  @override
  String get follow_label =>
      (super.noSuchMethod(
            Invocation.getter(#follow_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#follow_label),
            ),
          )
          as String);

  @override
  String get followed_label =>
      (super.noSuchMethod(
            Invocation.getter(#followed_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#followed_label),
            ),
          )
          as String);

  @override
  String get search_page_title =>
      (super.noSuchMethod(
            Invocation.getter(#search_page_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#search_page_title),
            ),
          )
          as String);

  @override
  String get cancel_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#cancel_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#cancel_button_label),
            ),
          )
          as String);

  @override
  String get user_label =>
      (super.noSuchMethod(
            Invocation.getter(#user_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#user_label),
            ),
          )
          as String);

  @override
  String get trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#trekking_label),
            ),
          )
          as String);

  @override
  String get no_user_found_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_user_found_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_user_found_label),
            ),
          )
          as String);

  @override
  String get no_trekking_found_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_trekking_found_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_trekking_found_label),
            ),
          )
          as String);

  @override
  String get no_diary_found_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_diary_found_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_diary_found_label),
            ),
          )
          as String);

  @override
  String get settings_page_title =>
      (super.noSuchMethod(
            Invocation.getter(#settings_page_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#settings_page_title),
            ),
          )
          as String);

  @override
  String get edit_profile_photo_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#edit_profile_photo_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#edit_profile_photo_button_label),
            ),
          )
          as String);

  @override
  String get name_field_label =>
      (super.noSuchMethod(
            Invocation.getter(#name_field_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#name_field_label),
            ),
          )
          as String);

  @override
  String get surname_field_label =>
      (super.noSuchMethod(
            Invocation.getter(#surname_field_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#surname_field_label),
            ),
          )
          as String);

  @override
  String get birthdate_field_label =>
      (super.noSuchMethod(
            Invocation.getter(#birthdate_field_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#birthdate_field_label),
            ),
          )
          as String);

  @override
  String get language_field_label =>
      (super.noSuchMethod(
            Invocation.getter(#language_field_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#language_field_label),
            ),
          )
          as String);

  @override
  String get language_selection_label =>
      (super.noSuchMethod(
            Invocation.getter(#language_selection_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#language_selection_label),
            ),
          )
          as String);

  @override
  String get starting_point_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#starting_point_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#starting_point_trekking_label),
            ),
          )
          as String);

  @override
  String get distance_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#distance_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#distance_trekking_label),
            ),
          )
          as String);

  @override
  String get estimated_time_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#estimated_time_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#estimated_time_trekking_label),
            ),
          )
          as String);

  @override
  String get elevaition_gain_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#elevaition_gain_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#elevaition_gain_trekking_label),
            ),
          )
          as String);

  @override
  String get ending_point_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#ending_point_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#ending_point_trekking_label),
            ),
          )
          as String);

  @override
  String get info_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#info_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#info_trekking_label),
            ),
          )
          as String);

  @override
  String get description_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#description_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#description_trekking_label),
            ),
          )
          as String);

  @override
  String get refreshment_point_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#refreshment_point_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#refreshment_point_trekking_label),
            ),
          )
          as String);

  @override
  String get refreshment_point_available_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#refreshment_point_available_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#refreshment_point_available_trekking_label),
            ),
          )
          as String);

  @override
  String get pic_nic_area_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#pic_nic_area_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pic_nic_area_trekking_label),
            ),
          )
          as String);

  @override
  String get pic_nic_area_available_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#pic_nic_area_available_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pic_nic_area_available_trekking_label),
            ),
          )
          as String);

  @override
  String get family_friendly_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#family_friendly_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#family_friendly_trekking_label),
            ),
          )
          as String);

  @override
  String get family_friendly_available_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#family_friendly_available_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#family_friendly_available_trekking_label),
            ),
          )
          as String);

  @override
  String get start_trekking_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#start_trekking_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#start_trekking_button_label),
            ),
          )
          as String);

  @override
  String get save_trekking_button_label =>
      (super.noSuchMethod(
            Invocation.getter(#save_trekking_button_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#save_trekking_button_label),
            ),
          )
          as String);

  @override
  String get challenges_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#challenges_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#challenges_trekking_label),
            ),
          )
          as String);

  @override
  String get challenges_available_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#challenges_available_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#challenges_available_trekking_label),
            ),
          )
          as String);

  @override
  String get hours_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#hours_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#hours_trekking_label),
            ),
          )
          as String);

  @override
  String get hour_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#hour_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#hour_trekking_label),
            ),
          )
          as String);

  @override
  String get minutes_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#minutes_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#minutes_trekking_label),
            ),
          )
          as String);

  @override
  String get weather_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#weather_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#weather_trekking_label),
            ),
          )
          as String);

  @override
  String get weather_trekking_botton =>
      (super.noSuchMethod(
            Invocation.getter(#weather_trekking_botton),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#weather_trekking_botton),
            ),
          )
          as String);

  @override
  String get details_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#details_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#details_trekking_label),
            ),
          )
          as String);

  @override
  String get start_question_label =>
      (super.noSuchMethod(
            Invocation.getter(#start_question_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#start_question_label),
            ),
          )
          as String);

  @override
  String get start_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#start_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#start_trekking_label),
            ),
          )
          as String);

  @override
  String get date_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#date_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#date_trekking_label),
            ),
          )
          as String);

  @override
  String get day_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#day_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#day_trekking_label),
            ),
          )
          as String);

  @override
  String get month_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#month_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#month_trekking_label),
            ),
          )
          as String);

  @override
  String get year_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#year_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#year_trekking_label),
            ),
          )
          as String);

  @override
  String get duration_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#duration_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#duration_trekking_label),
            ),
          )
          as String);

  @override
  String get friends_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#friends_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#friends_trekking_label),
            ),
          )
          as String);

  @override
  String get friends_selected_label =>
      (super.noSuchMethod(
            Invocation.getter(#friends_selected_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#friends_selected_label),
            ),
          )
          as String);

  @override
  String get choose_friend_label =>
      (super.noSuchMethod(
            Invocation.getter(#choose_friend_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#choose_friend_label),
            ),
          )
          as String);

  @override
  String get photos_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#photos_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#photos_trekking_label),
            ),
          )
          as String);

  @override
  String get refuge_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#refuge_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#refuge_trekking_label),
            ),
          )
          as String);

  @override
  String get yes_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#yes_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#yes_botton_label),
            ),
          )
          as String);

  @override
  String get no_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_botton_label),
            ),
          )
          as String);

  @override
  String get mood_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_trekking_label),
            ),
          )
          as String);

  @override
  String get mood_selected_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_selected_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_selected_label),
            ),
          )
          as String);

  @override
  String get choose_mood_label =>
      (super.noSuchMethod(
            Invocation.getter(#choose_mood_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#choose_mood_label),
            ),
          )
          as String);

  @override
  String get mood_love_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_love_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_love_label),
            ),
          )
          as String);

  @override
  String get mood_happy_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_happy_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_happy_label),
            ),
          )
          as String);

  @override
  String get mood_relaxed_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_relaxed_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_relaxed_label),
            ),
          )
          as String);

  @override
  String get mood_tired_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_tired_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_tired_label),
            ),
          )
          as String);

  @override
  String get mood_proud_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_proud_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_proud_label),
            ),
          )
          as String);

  @override
  String get mood_sad_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_sad_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_sad_label),
            ),
          )
          as String);

  @override
  String get mood_excited_label =>
      (super.noSuchMethod(
            Invocation.getter(#mood_excited_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#mood_excited_label),
            ),
          )
          as String);

  @override
  String get notes_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#notes_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#notes_trekking_label),
            ),
          )
          as String);

  @override
  String get notes_placeholder_trekking_label =>
      (super.noSuchMethod(
            Invocation.getter(#notes_placeholder_trekking_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#notes_placeholder_trekking_label),
            ),
          )
          as String);

  @override
  String get save_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#save_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#save_botton_label),
            ),
          )
          as String);

  @override
  String get add_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#add_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#add_botton_label),
            ),
          )
          as String);

  @override
  String get public_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#public_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#public_botton_label),
            ),
          )
          as String);

  @override
  String get private_botton_label =>
      (super.noSuchMethod(
            Invocation.getter(#private_botton_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#private_botton_label),
            ),
          )
          as String);

  @override
  String get public_private_label =>
      (super.noSuchMethod(
            Invocation.getter(#public_private_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#public_private_label),
            ),
          )
          as String);

  @override
  String get challenge_selected_label =>
      (super.noSuchMethod(
            Invocation.getter(#challenge_selected_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#challenge_selected_label),
            ),
          )
          as String);

  @override
  String get choose_challenge_label =>
      (super.noSuchMethod(
            Invocation.getter(#choose_challenge_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#choose_challenge_label),
            ),
          )
          as String);

  @override
  String get challeng_title =>
      (super.noSuchMethod(
            Invocation.getter(#challeng_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#challeng_title),
            ),
          )
          as String);

  @override
  String get no_challenge =>
      (super.noSuchMethod(
            Invocation.getter(#no_challenge),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_challenge),
            ),
          )
          as String);

  @override
  String get before_start =>
      (super.noSuchMethod(
            Invocation.getter(#before_start),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#before_start),
            ),
          )
          as String);

  @override
  String get back_label =>
      (super.noSuchMethod(
            Invocation.getter(#back_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#back_label),
            ),
          )
          as String);

  @override
  String get trekking_completed_label =>
      (super.noSuchMethod(
            Invocation.getter(#trekking_completed_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#trekking_completed_label),
            ),
          )
          as String);

  @override
  String get public_diaries_label =>
      (super.noSuchMethod(
            Invocation.getter(#public_diaries_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#public_diaries_label),
            ),
          )
          as String);

  @override
  String get private_diaries_label =>
      (super.noSuchMethod(
            Invocation.getter(#private_diaries_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#private_diaries_label),
            ),
          )
          as String);

  @override
  String get no_users_found_label =>
      (super.noSuchMethod(
            Invocation.getter(#no_users_found_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#no_users_found_label),
            ),
          )
          as String);

  @override
  String get title_notification_arrival =>
      (super.noSuchMethod(
            Invocation.getter(#title_notification_arrival),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_notification_arrival),
            ),
          )
          as String);

  @override
  String get body_notification_arrival =>
      (super.noSuchMethod(
            Invocation.getter(#body_notification_arrival),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_notification_arrival),
            ),
          )
          as String);

  @override
  String get alert_notification_arrival =>
      (super.noSuchMethod(
            Invocation.getter(#alert_notification_arrival),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_notification_arrival),
            ),
          )
          as String);

  @override
  String get title_challenge_balance =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_balance),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_balance),
            ),
          )
          as String);

  @override
  String get body_challenge_balance =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_balance),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_balance),
            ),
          )
          as String);

  @override
  String get alert_challenge_balance =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_balance),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_balance),
            ),
          )
          as String);

  @override
  String get title_challenge_hi =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_hi),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_hi),
            ),
          )
          as String);

  @override
  String get body_challenge_hi =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_hi),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_hi),
            ),
          )
          as String);

  @override
  String get alert_challenge_hi =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_hi),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_hi),
            ),
          )
          as String);

  @override
  String get title_challenge_mini_orientiring =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_mini_orientiring),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_mini_orientiring),
            ),
          )
          as String);

  @override
  String get body_challenge_mini_orientiring =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_mini_orientiring),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_mini_orientiring),
            ),
          )
          as String);

  @override
  String get alert_challenge_mini_orientiring =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_mini_orientiring),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_mini_orientiring),
            ),
          )
          as String);

  @override
  String get title_challenge_photo =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_photo),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_photo),
            ),
          )
          as String);

  @override
  String get body_challenge_photo =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_photo),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_photo),
            ),
          )
          as String);

  @override
  String get alert_challenge_photo =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_photo),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_photo),
            ),
          )
          as String);

  @override
  String get title_challenge_silent_walking =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_silent_walking),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_silent_walking),
            ),
          )
          as String);

  @override
  String get body_challenge_silent_walking =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_silent_walking),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_silent_walking),
            ),
          )
          as String);

  @override
  String get alert_challenge_silent_walking =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_silent_walking),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_silent_walking),
            ),
          )
          as String);

  @override
  String get title_challenge_time =>
      (super.noSuchMethod(
            Invocation.getter(#title_challenge_time),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title_challenge_time),
            ),
          )
          as String);

  @override
  String get body_challenge_time =>
      (super.noSuchMethod(
            Invocation.getter(#body_challenge_time),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#body_challenge_time),
            ),
          )
          as String);

  @override
  String get alert_challenge_time =>
      (super.noSuchMethod(
            Invocation.getter(#alert_challenge_time),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#alert_challenge_time),
            ),
          )
          as String);

  @override
  String get connect_label =>
      (super.noSuchMethod(
            Invocation.getter(#connect_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#connect_label),
            ),
          )
          as String);

  @override
  String get scan_qr_code_label =>
      (super.noSuchMethod(
            Invocation.getter(#scan_qr_code_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#scan_qr_code_label),
            ),
          )
          as String);

  @override
  String get qr_generated_label =>
      (super.noSuchMethod(
            Invocation.getter(#qr_generated_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#qr_generated_label),
            ),
          )
          as String);

  @override
  String get new_qr_label =>
      (super.noSuchMethod(
            Invocation.getter(#new_qr_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#new_qr_label),
            ),
          )
          as String);

  @override
  String get language_label =>
      (super.noSuchMethod(
            Invocation.getter(#language_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#language_label),
            ),
          )
          as String);

  @override
  String get home_label =>
      (super.noSuchMethod(
            Invocation.getter(#home_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#home_label),
            ),
          )
          as String);

  @override
  String get u_label =>
      (super.noSuchMethod(
            Invocation.getter(#u_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#u_label),
            ),
          )
          as String);

  @override
  String get follower_label =>
      (super.noSuchMethod(
            Invocation.getter(#follower_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#follower_label),
            ),
          )
          as String);

  @override
  String get following_label =>
      (super.noSuchMethod(
            Invocation.getter(#following_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#following_label),
            ),
          )
          as String);

  @override
  String get logout_label =>
      (super.noSuchMethod(
            Invocation.getter(#logout_label),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#logout_label),
            ),
          )
          as String);
}
