// Mocks generated by Mockito 5.4.6 from annotations
// in app_triplo_wearos/test/pages/HomePage/homepage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i12;

import 'package:app_triplo_wearos/controller/servicecontroller.dart' as _i13;
import 'package:app_triplo_wearos/controller/trekking.dart' as _i7;
import 'package:app_triplo_wearos/l10n/app_localizations.dart' as _i11;
import 'package:app_triplo_wearos/model/trekking.dart' as _i8;
import 'package:app_triplo_wearos/service/OSservice/geo.dart' as _i2;
import 'package:app_triplo_wearos/service/OSservice/memory.dart' as _i3;
import 'package:app_triplo_wearos/service/OSservice/notification.dart' as _i4;
import 'package:app_triplo_wearos/service/OSservice/permission_service.dart'
    as _i6;
import 'package:app_triplo_wearos/service/pairing_service.dart' as _i5;
import 'package:http/http.dart' as _i15;
import 'package:latlong2/latlong.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGeoService_0 extends _i1.SmartFake implements _i2.GeoService {
  _FakeGeoService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_1 extends _i1.SmartFake implements _i3.MemoryService {
  _FakeMemoryService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_2 extends _i1.SmartFake
    implements _i4.NotificationService {
  _FakeNotificationService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePairingService_3 extends _i1.SmartFake
    implements _i5.PairingService {
  _FakePairingService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_4 extends _i1.SmartFake
    implements _i6.PermissionService {
  _FakePermissionService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i7.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_0(this, Invocation.getter(#geo)),
          )
          as _i2.GeoService);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i4.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_2(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i4.NotificationService);

  @override
  _i5.PairingService get pairingService =>
      (super.noSuchMethod(
            Invocation.getter(#pairingService),
            returnValue: _FakePairingService_3(
              this,
              Invocation.getter(#pairingService),
            ),
          )
          as _i5.PairingService);

  @override
  List<_i8.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i8.Trekking>[],
          )
          as List<_i8.Trekking>);

  @override
  set onTrekkingSelected(void Function(_i8.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i8.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i8.Trekking?);

  @override
  _i9.Future<_i8.Trekking?> getTrekkingByIdAsync(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [documentId]),
            returnValue: _i9.Future<_i8.Trekking?>.value(),
          )
          as _i9.Future<_i8.Trekking?>);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i9.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i11.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<List<_i8.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i9.Future<List<_i8.Trekking>>.value(<_i8.Trekking>[]),
          )
          as _i9.Future<List<_i8.Trekking>>);

  @override
  _i9.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i13.ServiceController {
  MockServiceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i2.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_0(this, Invocation.getter(#geo)),
          )
          as _i2.GeoService);

  @override
  _i6.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_4(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i6.PermissionService);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i2.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i6.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i14.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i9.Future<_i14.LatLng?>.value(),
          )
          as _i9.Future<_i14.LatLng?>);

  @override
  _i9.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang, {
    _i15.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang], {#client: client}),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang, {
    _i15.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang], {#client: client}),
            returnValue: _i9.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i9.Future<List<Map<String, dynamic>>?>);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = false}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  _i9.Future<bool> hasInternet() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<List<Map<String, dynamic>>> mockAlerts({_i15.Client? client}) =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, [], {#client: client}),
            returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon, {
    _i15.Client? client,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon], {#client: client}),
            returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i9.Future<List<Map<String, dynamic>>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
          )
          as List<String>);
}
