// Mocks generated by Mockito 5.4.6 from annotations
// in app_triplo_wearos/test/pages/navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i2;

import 'package:app_triplo_wearos/controller/language.dart' as _i9;
import 'package:app_triplo_wearos/controller/trekking.dart' as _i10;
import 'package:app_triplo_wearos/controller/user.dart' as _i13;
import 'package:app_triplo_wearos/l10n/app_localizations.dart' as _i12;
import 'package:app_triplo_wearos/model/diary.dart' as _i15;
import 'package:app_triplo_wearos/model/trekking.dart' as _i11;
import 'package:app_triplo_wearos/model/user.dart' as _i14;
import 'package:app_triplo_wearos/service/OSservice/geo.dart' as _i3;
import 'package:app_triplo_wearos/service/OSservice/memory.dart' as _i4;
import 'package:app_triplo_wearos/service/OSservice/notification.dart' as _i5;
import 'package:app_triplo_wearos/service/pairing_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocale_0 extends _i1.SmartFake implements _i2.Locale {
  _FakeLocale_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_1 extends _i1.SmartFake implements _i3.GeoService {
  _FakeGeoService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_2 extends _i1.SmartFake implements _i4.MemoryService {
  _FakeMemoryService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_3 extends _i1.SmartFake
    implements _i5.NotificationService {
  _FakeNotificationService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePairingService_4 extends _i1.SmartFake
    implements _i6.PairingService {
  _FakePairingService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PairingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPairingService extends _i1.Mock implements _i6.PairingService {
  MockPairingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get watchId =>
      (super.noSuchMethod(
            Invocation.getter(#watchId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#watchId),
            ),
          )
          as String);

  @override
  bool get pairing =>
      (super.noSuchMethod(Invocation.getter(#pairing), returnValue: false)
          as bool);

  @override
  bool get remoteLogoutActive =>
      (super.noSuchMethod(
            Invocation.getter(#remoteLogoutActive),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasValidPairId =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidPairId),
            returnValue: false,
          )
          as bool);

  @override
  set testPairingError(String? v) => super.noSuchMethod(
    Invocation.setter(#testPairingError, v),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> startWatchPairing({bool? forceNew = false}) =>
      (super.noSuchMethod(
            Invocation.method(#startWatchPairing, [], {#forceNew: forceNew}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> restoreWatchPairing() =>
      (super.noSuchMethod(
            Invocation.method(#restoreWatchPairing, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> resetPairingOnLogout({bool? regenerateQr = true}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPairingOnLogout, [], {
              #regenerateQr: regenerateQr,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logoutWatch() =>
      (super.noSuchMethod(
            Invocation.method(#logoutWatch, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Language].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguage extends _i1.Mock implements _i9.Language {
  MockLanguage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_0(this, Invocation.getter(#locale)),
          )
          as _i2.Locale);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> setLocale(_i2.Locale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadSavedLocale() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedLocale, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i10.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_1(this, Invocation.getter(#geo)),
          )
          as _i3.GeoService);

  @override
  _i4.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_2(this, Invocation.getter(#memory)),
          )
          as _i4.MemoryService);

  @override
  _i5.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_3(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i5.NotificationService);

  @override
  _i6.PairingService get pairingService =>
      (super.noSuchMethod(
            Invocation.getter(#pairingService),
            returnValue: _FakePairingService_4(
              this,
              Invocation.getter(#pairingService),
            ),
          )
          as _i6.PairingService);

  @override
  List<_i11.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i11.Trekking>[],
          )
          as List<_i11.Trekking>);

  @override
  set onTrekkingSelected(void Function(_i11.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i11.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i11.Trekking?);

  @override
  _i8.Future<_i11.Trekking?> getTrekkingByIdAsync(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [documentId]),
            returnValue: _i8.Future<_i11.Trekking?>.value(),
          )
          as _i8.Future<_i11.Trekking?>);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i8.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i12.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i11.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i8.Future<List<_i11.Trekking>>.value(
              <_i11.Trekking>[],
            ),
          )
          as _i8.Future<List<_i11.Trekking>>);

  @override
  _i8.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i13.UserController {
  MockUserController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadCurrentPairedUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentPairedUser, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i14.Users?> getUserById(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [uid]),
            returnValue: _i8.Future<_i14.Users?>.value(),
          )
          as _i8.Future<_i14.Users?>);

  @override
  _i8.Future<List<_i14.Users>> getFollowers(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [uid]),
            returnValue: _i8.Future<List<_i14.Users>>.value(<_i14.Users>[]),
          )
          as _i8.Future<List<_i14.Users>>);

  @override
  _i8.Future<List<_i14.Users>> getFollowing(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [uid]),
            returnValue: _i8.Future<List<_i14.Users>>.value(<_i14.Users>[]),
          )
          as _i8.Future<List<_i14.Users>>);

  @override
  _i8.Future<List<_i14.Users>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i8.Future<List<_i14.Users>>.value(<_i14.Users>[]),
          )
          as _i8.Future<List<_i14.Users>>);

  @override
  _i8.Future<_i15.Diary?> getDiaryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryById, [id]),
            returnValue: _i8.Future<_i15.Diary?>.value(),
          )
          as _i8.Future<_i15.Diary?>);

  @override
  _i8.Future<List<_i15.Diary>> getPublicDiaries(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicDiaries, [uid]),
            returnValue: _i8.Future<List<_i15.Diary>>.value(<_i15.Diary>[]),
          )
          as _i8.Future<List<_i15.Diary>>);

  @override
  _i8.Future<List<_i15.Diary>> getPrivateDiaries(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateDiaries, [uid]),
            returnValue: _i8.Future<List<_i15.Diary>>.value(<_i15.Diary>[]),
          )
          as _i8.Future<List<_i15.Diary>>);

  @override
  _i8.Future<List<String>> getFollowerUids(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerUids, [uid]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> getFollowingUids(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingUids, [uid]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
