// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/LoginRegistrationPage/LoginPage/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i3;
import 'dart:ui' as _i11;

import 'package:flutter/material.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:triplo/controller/diary.dart' as _i12;
import 'package:triplo/controller/trekking.dart' as _i13;
import 'package:triplo/controller/user.dart' as _i7;
import 'package:triplo/l10n/app_localizations.dart' as _i15;
import 'package:triplo/model/diary.dart' as _i2;
import 'package:triplo/model/trekking.dart' as _i14;
import 'package:triplo/model/user.dart' as _i9;
import 'package:triplo/service/authservice.dart' as _i4;
import 'package:triplo/service/memory.dart' as _i5;
import 'package:triplo/service/notification.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiary_0 extends _i1.SmartFake implements _i2.Diary {
  _FakeDiary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_1 extends _i1.SmartFake implements _i3.File {
  _FakeFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_2 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_3 extends _i1.SmartFake implements _i5.MemoryService {
  _FakeMemoryService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_4 extends _i1.SmartFake
    implements _i6.NotificationService {
  _FakeNotificationService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i7.UserController {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isGoogleUser =>
      (super.noSuchMethod(
            Invocation.getter(#isGoogleUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPasswordUser =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.Users?> getUserById(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [uid]),
            returnValue: _i8.Future<_i9.Users?>.value(),
            returnValueForMissingStub: _i8.Future<_i9.Users?>.value(),
          )
          as _i8.Future<_i9.Users?>);

  @override
  _i8.Future<List<_i9.Users>> getFollowers(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [uid]),
            returnValue: _i8.Future<List<_i9.Users>>.value(<_i9.Users>[]),
            returnValueForMissingStub: _i8.Future<List<_i9.Users>>.value(
              <_i9.Users>[],
            ),
          )
          as _i8.Future<List<_i9.Users>>);

  @override
  _i8.Future<List<_i9.Users>> getFollowing(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [uid]),
            returnValue: _i8.Future<List<_i9.Users>>.value(<_i9.Users>[]),
            returnValueForMissingStub: _i8.Future<List<_i9.Users>>.value(
              <_i9.Users>[],
            ),
          )
          as _i8.Future<List<_i9.Users>>);

  @override
  _i8.Future<List<String>> getFollowingIds(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingIds, [uid]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i9.Users>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i8.Future<List<_i9.Users>>.value(<_i9.Users>[]),
            returnValueForMissingStub: _i8.Future<List<_i9.Users>>.value(
              <_i9.Users>[],
            ),
          )
          as _i8.Future<List<_i9.Users>>);

  @override
  _i8.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSurname(String? surname) =>
      (super.noSuchMethod(
            Invocation.method(#updateSurname, [surname]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateBirthdate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#updateBirthdate, [date]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateProfilePhoto(_i3.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [image]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> requestPasswordReset() =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> restoreGoogleProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoogleProfilePhoto, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserLevel(String? difficulty) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLevel, [difficulty]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isFollowing(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [targetUid]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> followUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [targetUid]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> unfollowUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [targetUid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  ({String token, String watchId}) extractWatchPair(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#extractWatchPair, [raw]),
            returnValue: (
              token: _i10.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i10.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
            returnValueForMissingStub: (
              token: _i10.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i10.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
          )
          as ({String token, String watchId}));

  @override
  _i8.Future<void> approveWatchPair({
    required String? watchId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveWatchPair, [], {
              #watchId: watchId,
              #token: token,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> changeEmail({
    required String? newEmail,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {
              #newEmail: newEmail,
              #currentPassword: currentPassword,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshEmailFromAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEmailFromAuth, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getConnectedWatches() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedWatches, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> enableRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#enableRemoteLogoutForWatch, [watchId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearRemoteLogoutForWatch, [watchId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DiaryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryController extends _i1.Mock implements _i12.DiaryController {
  @override
  List<_i2.Diary> get allDiaries =>
      (super.noSuchMethod(
            Invocation.getter(#allDiaries),
            returnValue: <_i2.Diary>[],
            returnValueForMissingStub: <_i2.Diary>[],
          )
          as List<_i2.Diary>);

  @override
  set currentUser(_i9.Users? user) => super.noSuchMethod(
    Invocation.setter(#currentUser, user),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.Diary updateDiary(
    _i2.Diary? page,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [
              page,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
            ]),
            returnValue: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
            returnValueForMissingStub: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
          )
          as _i2.Diary);

  @override
  _i2.Diary? getDiaryById(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryById, [documentId]),
            returnValueForMissingStub: null,
          )
          as _i2.Diary?);

  @override
  _i8.Future<void> addDiary(
    String? title,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
    bool? modify,
    String? diaryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDiary, [
              title,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
              modify,
              diaryId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeDiary(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDiary, [diaryId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.Diary>?> fetchDiaryById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryById, [userId]),
            returnValue: _i8.Future<List<_i2.Diary>?>.value(),
            returnValueForMissingStub: _i8.Future<List<_i2.Diary>?>.value(),
          )
          as _i8.Future<List<_i2.Diary>?>);

  @override
  _i8.Future<List<String>> uploadDiaryImages(List<_i3.File>? images) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDiaryImages, [images]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String?> getDownloadUrlChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrlChild, [path]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deletePhotoFromDb(String? diaryId, String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhotoFromDb, [diaryId, photoPath]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.Diary>> getRandomPublicDiariesFromFollowing({
    required List<String>? followingIds,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomPublicDiariesFromFollowing, [], {
              #followingIds: followingIds,
              #limit: limit,
            }),
            returnValue: _i8.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i8.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i8.Future<List<_i2.Diary>>);

  @override
  _i8.Future<List<_i2.Diary>> getPublicDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicDiaries, [userId]),
            returnValue: _i8.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i8.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i8.Future<List<_i2.Diary>>);

  @override
  _i8.Future<List<_i2.Diary>> getPrivateDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateDiaries, [userId]),
            returnValue: _i8.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i8.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i8.Future<List<_i2.Diary>>);

  @override
  _i8.Future<_i2.Diary?> getDiaryByIdAsync(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryByIdAsync, [diaryId]),
            returnValue: _i8.Future<_i2.Diary?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.Diary?>.value(),
          )
          as _i8.Future<_i2.Diary?>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i5.MemoryService {
  @override
  _i8.Future<_i3.File?> getImageFromDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromDisk, [url]),
            returnValue: _i8.Future<_i3.File?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.File?>.value(),
          )
          as _i8.Future<_i3.File?>);

  @override
  _i8.Future<_i3.File> cacheImageOnDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImageOnDisk, [url]),
            returnValue: _i8.Future<_i3.File>.value(
              _FakeFile_1(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.File>.value(
              _FakeFile_1(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
          )
          as _i8.Future<_i3.File>);

  @override
  _i8.Future<_i3.File?> getImageFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromMemory, [key]),
            returnValue: _i8.Future<_i3.File?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.File?>.value(),
          )
          as _i8.Future<_i3.File?>);

  @override
  void saveImageToMemory(String? key, _i3.File? file) => super.noSuchMethod(
    Invocation.method(#saveImageToMemory, [key, file]),
    returnValueForMissingStub: null,
  );

  @override
  void removeImageFromMemory(String? key) => super.noSuchMethod(
    Invocation.method(#removeImageFromMemory, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<String?> getSavedLocaleCode() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocaleCode, []),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> saveLocaleCode(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocaleCode, [localeCode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Set<String>> getShownWeatherAlertKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getShownWeatherAlertKeys, []),
            returnValue: _i8.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i8.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i8.Future<Set<String>>);

  @override
  _i8.Future<void> saveShownWeatherAlertKeys(Set<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#saveShownWeatherAlertKeys, [keys]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#addShownWeatherAlertKey, [key]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> hasShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasShownWeatherAlertKey, [key]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i13.TrekkingController {
  @override
  _i4.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_2(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_2(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i4.AuthService);

  @override
  _i5.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_3(this, Invocation.getter(#memory)),
            returnValueForMissingStub: _FakeMemoryService_3(
              this,
              Invocation.getter(#memory),
            ),
          )
          as _i5.MemoryService);

  @override
  _i6.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_4(
              this,
              Invocation.getter(#notification),
            ),
            returnValueForMissingStub: _FakeNotificationService_4(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i6.NotificationService);

  @override
  List<_i14.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i14.Trekking>[],
            returnValueForMissingStub: <_i14.Trekking>[],
          )
          as List<_i14.Trekking>);

  @override
  set authService(_i4.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i5.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set notification(_i6.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i14.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i14.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingById, [documentId]),
            returnValueForMissingStub: null,
          )
          as _i14.Trekking?);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingId, [name]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i8.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i14.Trekking>> searchTrekking(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrekking, [query]),
            returnValue: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
          )
          as _i8.Future<List<_i14.Trekking>>);

  @override
  _i8.Future<_i14.Trekking?> fetchTrekkingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrekkingById, [id]),
            returnValue: _i8.Future<_i14.Trekking?>.value(),
            returnValueForMissingStub: _i8.Future<_i14.Trekking?>.value(),
          )
          as _i8.Future<_i14.Trekking?>);

  @override
  _i8.Future<List<_i14.Trekking>> getSavedTrekkings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedTrekkings, [uid]),
            returnValue: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
          )
          as _i8.Future<List<_i14.Trekking>>);

  @override
  _i8.Future<void> addTrekkingToSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrekkingToSaved, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTrekkingFromSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrekkingFromSaved, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isTrekkingSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrekkingSaved, [trekkingId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i8.Future<_i3.File?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.File?>.value(),
          )
          as _i8.Future<_i3.File?>);

  @override
  _i8.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i15.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.File>> getCachedImages(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImages, [imagePaths]),
            returnValue: _i8.Future<List<_i3.File>>.value(<_i3.File>[]),
            returnValueForMissingStub: _i8.Future<List<_i3.File>>.value(
              <_i3.File>[],
            ),
          )
          as _i8.Future<List<_i3.File>>);

  @override
  _i8.Future<_i14.Trekking?> getTrekkingByIdAsync(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [trekkingId]),
            returnValue: _i8.Future<_i14.Trekking?>.value(),
            returnValueForMissingStub: _i8.Future<_i14.Trekking?>.value(),
          )
          as _i8.Future<_i14.Trekking?>);

  @override
  _i8.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i14.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i14.Trekking>>.value(
              <_i14.Trekking>[],
            ),
          )
          as _i8.Future<List<_i14.Trekking>>);

  @override
  _i8.Future<void> updateWeatherNotificationLastCheck() =>
      (super.noSuchMethod(
            Invocation.method(#updateWeatherNotificationLastCheck, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i16.NavigatorObserver {
  @override
  void didPush(
    _i16.Route<dynamic>? route,
    _i16.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i16.Route<dynamic>? route,
    _i16.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i16.Route<dynamic>? newRoute,
    _i16.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i16.Route<dynamic>? topRoute,
    _i16.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i16.Route<dynamic>? route,
    _i16.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
