// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/main_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i2;
import 'dart:ui' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i17;
import 'package:firebase_storage/firebase_storage.dart' as _i9;
import 'package:flutter/material.dart' as _i19;
import 'package:flutter/services.dart' as _i22;
import 'package:geolocator/geolocator.dart' as _i15;
import 'package:http/http.dart' as _i12;
import 'package:latlong2/latlong.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:permission_handler/permission_handler.dart' as _i18;
import 'package:triplo/controller/challenge.dart' as _i29;
import 'package:triplo/controller/diary.dart' as _i28;
import 'package:triplo/controller/language.dart' as _i20;
import 'package:triplo/controller/servicecontroller.dart' as _i5;
import 'package:triplo/controller/trekking.dart' as _i25;
import 'package:triplo/controller/user.dart' as _i23;
import 'package:triplo/l10n/app_localizations.dart' as _i27;
import 'package:triplo/model/challenges.dart' as _i30;
import 'package:triplo/model/diary.dart' as _i8;
import 'package:triplo/model/trekking.dart' as _i26;
import 'package:triplo/model/user.dart' as _i24;
import 'package:triplo/service/authservice.dart' as _i6;
import 'package:triplo/service/geo.dart' as _i10;
import 'package:triplo/service/internetservice.dart' as _i21;
import 'package:triplo/service/memory.dart' as _i3;
import 'package:triplo/service/notification.dart' as _i7;
import 'package:triplo/service/permission.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_1 extends _i1.SmartFake implements _i3.MemoryService {
  _FakeMemoryService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServiceController_3 extends _i1.SmartFake
    implements _i5.ServiceController {
  _FakeServiceController_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_5 extends _i1.SmartFake implements _i6.AuthService {
  _FakeAuthService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_6 extends _i1.SmartFake
    implements _i7.NotificationService {
  _FakeNotificationService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiary_7 extends _i1.SmartFake implements _i8.Diary {
  _FakeDiary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_8 extends _i1.SmartFake
    implements _i9.FirebaseStorage {
  _FakeFirebaseStorage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_9 extends _i1.SmartFake implements _i10.GeoService {
  _FakeGeoService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_10 extends _i1.SmartFake
    implements _i11.PermissionService {
  _FakePermissionService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_11 extends _i1.SmartFake implements _i12.Client {
  _FakeClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationLocationState_12 extends _i1.SmartFake
    implements _i5.NavigationLocationState {
  _FakeNavigationLocationState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i3.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.File?> getImageFromDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromDisk, [url]),
            returnValue: _i13.Future<_i2.File?>.value(),
          )
          as _i13.Future<_i2.File?>);

  @override
  _i13.Future<_i2.File> cacheImageOnDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImageOnDisk, [url]),
            returnValue: _i13.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
          )
          as _i13.Future<_i2.File>);

  @override
  _i13.Future<_i2.File?> getImageFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromMemory, [key]),
            returnValue: _i13.Future<_i2.File?>.value(),
          )
          as _i13.Future<_i2.File?>);

  @override
  void saveImageToMemory(String? key, _i2.File? file) => super.noSuchMethod(
    Invocation.method(#saveImageToMemory, [key, file]),
    returnValueForMissingStub: null,
  );

  @override
  void removeImageFromMemory(String? key) => super.noSuchMethod(
    Invocation.method(#removeImageFromMemory, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<String?> getSavedLocaleCode() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocaleCode, []),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<void> saveLocaleCode(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocaleCode, [localeCode]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Set<String>> getShownWeatherAlertKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getShownWeatherAlertKeys, []),
            returnValue: _i13.Future<Set<String>>.value(<String>{}),
          )
          as _i13.Future<Set<String>>);

  @override
  _i13.Future<void> saveShownWeatherAlertKeys(Set<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#saveShownWeatherAlertKeys, [keys]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> addShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#addShownWeatherAlertKey, [key]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> hasShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasShownWeatherAlertKey, [key]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [GeoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoService extends _i1.Mock implements _i10.GeoService {
  MockGeoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i14.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i13.Future<_i14.LatLng?>.value(),
          )
          as _i13.Future<_i14.LatLng?>);

  @override
  _i13.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Stream<_i15.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i13.Stream<_i15.Position>.empty(),
          )
          as _i13.Stream<_i15.Position>);

  @override
  _i13.Future<bool> openLocationSettingsPage() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettingsPage, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i13.Stream<double?>.empty(),
          )
          as _i13.Stream<double?>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isGoogleUser =>
      (super.noSuchMethod(Invocation.getter(#isGoogleUser), returnValue: false)
          as bool);

  @override
  bool get isPasswordUser =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUser),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> sendPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [email]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> requestPasswordReset() =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  ({String token, String watchId}) extractWatchPair(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#extractWatchPair, [raw]),
            returnValue: (
              token: _i16.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i16.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
          )
          as ({String token, String watchId}));

  @override
  _i13.Future<void> approveWatchPair({
    required String? watchId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveWatchPair, [], {
              #watchId: watchId,
              #token: token,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> changeEmail({
    required String? newEmail,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {
              #newEmail: newEmail,
              #currentPassword: currentPassword,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> refreshEmailFromAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEmailFromAuth, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<Map<String, dynamic>>> getConnectedWatches() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedWatches, []),
            returnValue: _i13.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i13.Future<List<Map<String, dynamic>>>);

  @override
  _i13.Future<void> enableRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#enableRemoteLogoutForWatch, [watchId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> clearRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearRemoteLogoutForWatch, [watchId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> ensureUserFirestoreDocsPublic(_i17.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserFirestoreDocsPublic, [user]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i11.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> askPermissionsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#askPermissionsOnce, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i18.PermissionStatus> locationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#locationStatus, []),
            returnValue: _i13.Future<_i18.PermissionStatus>.value(
              _i18.PermissionStatus.denied,
            ),
          )
          as _i13.Future<_i18.PermissionStatus>);

  @override
  _i13.Future<bool> isLocationGranted() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationGranted, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> isLocationDenied() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationDenied, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> openAppSettingsPage() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettingsPage, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setNavKey(_i19.GlobalKey<_i19.NavigatorState>? key) =>
      super.noSuchMethod(
        Invocation.method(#setNavKey, [key]),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> showTrekkingNotification({
    required int? id,
    required String? title,
    required String? body,
    required String? payload,
    String? channelId = 'notifications_channel',
    String? channelName = 'Notifications',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showTrekkingNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
              #channelId: channelId,
              #channelName: channelName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> showWeatherNotification({
    required int? id,
    required String? title,
    required String? body,
    String? payload = 'weather_alert',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showWeatherNotification, [], {
              #id: id,
              #title: title,
              #body: body,
              #payload: payload,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [Language].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguage extends _i1.Mock implements _i20.Language {
  MockLanguage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MemoryService get memoryService =>
      (super.noSuchMethod(
            Invocation.getter(#memoryService),
            returnValue: _FakeMemoryService_1(
              this,
              Invocation.getter(#memoryService),
            ),
          )
          as _i3.MemoryService);

  @override
  _i4.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_2(this, Invocation.getter(#locale)),
          )
          as _i4.Locale);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> loadSavedLocale() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedLocale, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setLocale(_i4.Locale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InternetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetService extends _i1.Mock implements _i21.InternetService {
  MockInternetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ServiceController get servicecontroller =>
      (super.noSuchMethod(
            Invocation.getter(#servicecontroller),
            returnValue: _FakeServiceController_3(
              this,
              Invocation.getter(#servicecontroller),
            ),
          )
          as _i5.ServiceController);

  @override
  Duration get checkEvery =>
      (super.noSuchMethod(
            Invocation.getter(#checkEvery),
            returnValue: _FakeDuration_4(this, Invocation.getter(#checkEvery)),
          )
          as Duration);

  @override
  Duration get offlineThreshold =>
      (super.noSuchMethod(
            Invocation.getter(#offlineThreshold),
            returnValue: _FakeDuration_4(
              this,
              Invocation.getter(#offlineThreshold),
            ),
          )
          as Duration);

  @override
  Duration get resumeGracePeriod =>
      (super.noSuchMethod(
            Invocation.getter(#resumeGracePeriod),
            returnValue: _FakeDuration_4(
              this,
              Invocation.getter(#resumeGracePeriod),
            ),
          )
          as Duration);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );

  @override
  void forceRecheck() => super.noSuchMethod(
    Invocation.method(#forceRecheck, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i4.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  bool handleStartBackGesture(_i22.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i22.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> didPushRouteInformation(
    _i19.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i4.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i4.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i4.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i13.Future<_i4.AppExitResponse>.value(
              _i4.AppExitResponse.exit,
            ),
          )
          as _i13.Future<_i4.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i23.UserController {
  MockUserController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isGoogleUser =>
      (super.noSuchMethod(Invocation.getter(#isGoogleUser), returnValue: false)
          as bool);

  @override
  bool get isPasswordUser =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUser),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i24.Users?> getUserById(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [uid]),
            returnValue: _i13.Future<_i24.Users?>.value(),
          )
          as _i13.Future<_i24.Users?>);

  @override
  _i13.Future<List<_i24.Users>> getFollowers(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [uid]),
            returnValue: _i13.Future<List<_i24.Users>>.value(<_i24.Users>[]),
          )
          as _i13.Future<List<_i24.Users>>);

  @override
  _i13.Future<List<_i24.Users>> getFollowing(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [uid]),
            returnValue: _i13.Future<List<_i24.Users>>.value(<_i24.Users>[]),
          )
          as _i13.Future<List<_i24.Users>>);

  @override
  _i13.Future<List<String>> getFollowingIds(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingIds, [uid]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<List<_i24.Users>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i13.Future<List<_i24.Users>>.value(<_i24.Users>[]),
          )
          as _i13.Future<List<_i24.Users>>);

  @override
  _i13.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateSurname(String? surname) =>
      (super.noSuchMethod(
            Invocation.method(#updateSurname, [surname]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateBirthdate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#updateBirthdate, [date]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateProfilePhoto(_i2.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [image]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> sendPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [email]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> requestPasswordReset() =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> restoreGoogleProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoogleProfilePhoto, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateUserLevel(String? difficulty) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLevel, [difficulty]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isFollowing(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [targetUid]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> followUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [targetUid]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> unfollowUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [targetUid]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  ({String token, String watchId}) extractWatchPair(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#extractWatchPair, [raw]),
            returnValue: (
              token: _i16.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i16.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
          )
          as ({String token, String watchId}));

  @override
  _i13.Future<void> approveWatchPair({
    required String? watchId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveWatchPair, [], {
              #watchId: watchId,
              #token: token,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> changeEmail({
    required String? newEmail,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {
              #newEmail: newEmail,
              #currentPassword: currentPassword,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> refreshEmailFromAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEmailFromAuth, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<Map<String, dynamic>>> getConnectedWatches() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedWatches, []),
            returnValue: _i13.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i13.Future<List<Map<String, dynamic>>>);

  @override
  _i13.Future<void> enableRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#enableRemoteLogoutForWatch, [watchId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> clearRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearRemoteLogoutForWatch, [watchId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i25.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_5(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i6.AuthService);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i7.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_6(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i7.NotificationService);

  @override
  List<_i26.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i26.Trekking>[],
          )
          as List<_i26.Trekking>);

  @override
  set authService(_i6.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set notification(_i7.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i26.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i26.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i26.Trekking?);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i13.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<List<_i26.Trekking>> searchTrekking(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrekking, [query]),
            returnValue: _i13.Future<List<_i26.Trekking>>.value(
              <_i26.Trekking>[],
            ),
          )
          as _i13.Future<List<_i26.Trekking>>);

  @override
  _i13.Future<_i26.Trekking?> fetchTrekkingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrekkingById, [id]),
            returnValue: _i13.Future<_i26.Trekking?>.value(),
          )
          as _i13.Future<_i26.Trekking?>);

  @override
  _i13.Future<List<_i26.Trekking>> getSavedTrekkings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedTrekkings, [uid]),
            returnValue: _i13.Future<List<_i26.Trekking>>.value(
              <_i26.Trekking>[],
            ),
          )
          as _i13.Future<List<_i26.Trekking>>);

  @override
  _i13.Future<void> addTrekkingToSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrekkingToSaved, [trekkingId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> removeTrekkingFromSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrekkingFromSaved, [trekkingId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isTrekkingSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrekkingSaved, [trekkingId]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i2.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i13.Future<_i2.File?>.value(),
          )
          as _i13.Future<_i2.File?>);

  @override
  _i13.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i27.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i2.File>> getCachedImages(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImages, [imagePaths]),
            returnValue: _i13.Future<List<_i2.File>>.value(<_i2.File>[]),
          )
          as _i13.Future<List<_i2.File>>);

  @override
  _i13.Future<_i26.Trekking?> getTrekkingByIdAsync(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [trekkingId]),
            returnValue: _i13.Future<_i26.Trekking?>.value(),
          )
          as _i13.Future<_i26.Trekking?>);

  @override
  _i13.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<List<_i26.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i13.Future<List<_i26.Trekking>>.value(
              <_i26.Trekking>[],
            ),
          )
          as _i13.Future<List<_i26.Trekking>>);

  @override
  _i13.Future<void> updateWeatherNotificationLastCheck() =>
      (super.noSuchMethod(
            Invocation.method(#updateWeatherNotificationLastCheck, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DiaryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryController extends _i1.Mock implements _i28.DiaryController {
  MockDiaryController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Diary> get allDiaries =>
      (super.noSuchMethod(
            Invocation.getter(#allDiaries),
            returnValue: <_i8.Diary>[],
          )
          as List<_i8.Diary>);

  @override
  set currentUser(_i24.Users? user) => super.noSuchMethod(
    Invocation.setter(#currentUser, user),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Diary updateDiary(
    _i8.Diary? page,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [
              page,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
            ]),
            returnValue: _FakeDiary_7(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
          )
          as _i8.Diary);

  @override
  _i8.Diary? getDiaryById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getDiaryById, [documentId]))
          as _i8.Diary?);

  @override
  _i13.Future<void> addDiary(
    String? title,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
    bool? modify,
    String? diaryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDiary, [
              title,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
              modify,
              diaryId,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> removeDiary(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDiary, [diaryId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i8.Diary>?> fetchDiaryById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryById, [userId]),
            returnValue: _i13.Future<List<_i8.Diary>?>.value(),
          )
          as _i13.Future<List<_i8.Diary>?>);

  @override
  _i13.Future<List<String>> uploadDiaryImages(List<_i2.File>? images) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDiaryImages, [images]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<String?> getDownloadUrlChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrlChild, [path]),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<String?> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<void> deletePhotoFromDb(String? diaryId, String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhotoFromDb, [diaryId, photoPath]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i8.Diary>> getRandomPublicDiariesFromFollowing({
    required List<String>? followingIds,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomPublicDiariesFromFollowing, [], {
              #followingIds: followingIds,
              #limit: limit,
            }),
            returnValue: _i13.Future<List<_i8.Diary>>.value(<_i8.Diary>[]),
          )
          as _i13.Future<List<_i8.Diary>>);

  @override
  _i13.Future<List<_i8.Diary>> getPublicDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicDiaries, [userId]),
            returnValue: _i13.Future<List<_i8.Diary>>.value(<_i8.Diary>[]),
          )
          as _i13.Future<List<_i8.Diary>>);

  @override
  _i13.Future<List<_i8.Diary>> getPrivateDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateDiaries, [userId]),
            returnValue: _i13.Future<List<_i8.Diary>>.value(<_i8.Diary>[]),
          )
          as _i13.Future<List<_i8.Diary>>);

  @override
  _i13.Future<_i8.Diary?> getDiaryByIdAsync(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryByIdAsync, [diaryId]),
            returnValue: _i13.Future<_i8.Diary?>.value(),
          )
          as _i13.Future<_i8.Diary?>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChallengesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockChallengesController extends _i1.Mock
    implements _i29.ChallengesController {
  MockChallengesController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_8(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i9.FirebaseStorage);

  @override
  _i7.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_6(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i7.NotificationService);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  List<_i30.Challenges> get allChallenges =>
      (super.noSuchMethod(
            Invocation.getter(#allChallenges),
            returnValue: <_i30.Challenges>[],
          )
          as List<_i30.Challenges>);

  @override
  set notification(_i7.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i30.Challenges)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> loadChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#loadChallenges, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i30.Challenges? getChallengesById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getChallengesById, [documentId]))
          as _i30.Challenges?);

  @override
  _i13.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<_i2.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i13.Future<_i2.File?>.value(),
          )
          as _i13.Future<_i2.File?>);

  @override
  void notifyNewChallenge(
    String? challengeType,
    _i27.AppLocalizations? local,
  ) => super.noSuchMethod(
    Invocation.method(#notifyNewChallenge, [challengeType, local]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i5.ServiceController {
  MockServiceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i3.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_1(this, Invocation.getter(#memory)),
          )
          as _i3.MemoryService);

  @override
  _i10.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_9(this, Invocation.getter(#geo)),
          )
          as _i10.GeoService);

  @override
  _i11.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_10(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i11.PermissionService);

  @override
  _i12.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_11(this, Invocation.getter(#client)),
          )
          as _i12.Client);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i3.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i10.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i11.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  String weatherTile(String? layer) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTile, [layer]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
          )
          as String);

  @override
  String? resolveLayer(String? id) =>
      (super.noSuchMethod(Invocation.method(#resolveLayer, [id])) as String?);

  @override
  _i13.Future<_i14.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i13.Future<_i14.LatLng?>.value(),
          )
          as _i13.Future<_i14.LatLng?>);

  @override
  _i13.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang]),
            returnValue: _i13.Future<Map<String, dynamic>?>.value(),
          )
          as _i13.Future<Map<String, dynamic>?>);

  @override
  _i13.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang]),
            returnValue: _i13.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i13.Future<List<Map<String, dynamic>>?>);

  @override
  _i13.Future<bool> hasInternet([
    _i13.Future<List<_i2.InternetAddress>> Function(String)? lookup,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, [lookup]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = true}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i13.Future<List<Map<String, dynamic>>> mockAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, []),
            returnValue: _i13.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i13.Future<List<Map<String, dynamic>>>);

  @override
  _i13.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon]),
            returnValue: _i13.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i13.Future<List<Map<String, dynamic>>>);

  @override
  _i13.Future<_i5.NavigationLocationState> loadNavigationLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadNavigationLocation, []),
            returnValue: _i13.Future<_i5.NavigationLocationState>.value(
              _FakeNavigationLocationState_12(
                this,
                Invocation.method(#loadNavigationLocation, []),
              ),
            ),
          )
          as _i13.Future<_i5.NavigationLocationState>);

  @override
  _i13.Stream<_i15.Position> navigationPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#navigationPositionStream, []),
            returnValue: _i13.Stream<_i15.Position>.empty(),
          )
          as _i13.Stream<_i15.Position>);

  @override
  _i13.Future<void> openGpsSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openGpsSettings, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> openPermissionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openPermissionSettings, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  String googleSatelliteTile() =>
      (super.noSuchMethod(
            Invocation.method(#googleSatelliteTile, []),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
          )
          as String);

  @override
  String weatherTileFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTileFromId, [id]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
          )
          as String);

  @override
  String legendTypeFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#legendTypeFromId, [id]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
          )
          as String);

  @override
  _i13.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i13.Stream<double?>.empty(),
          )
          as _i13.Stream<double?>);
}
