// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/UserProfilePage/user_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i10;
import 'dart:ui' as _i15;

import 'package:geolocator/geolocator.dart' as _i21;
import 'package:http/http.dart' as _i8;
import 'package:latlong2/latlong.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:triplo/controller/diary.dart' as _i16;
import 'package:triplo/controller/servicecontroller.dart' as _i9;
import 'package:triplo/controller/trekking.dart' as _i17;
import 'package:triplo/controller/user.dart' as _i11;
import 'package:triplo/l10n/app_localizations.dart' as _i19;
import 'package:triplo/model/diary.dart' as _i2;
import 'package:triplo/model/trekking.dart' as _i18;
import 'package:triplo/model/user.dart' as _i13;
import 'package:triplo/service/authservice.dart' as _i3;
import 'package:triplo/service/geo.dart' as _i6;
import 'package:triplo/service/memory.dart' as _i4;
import 'package:triplo/service/notification.dart' as _i5;
import 'package:triplo/service/permission.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiary_0 extends _i1.SmartFake implements _i2.Diary {
  _FakeDiary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMemoryService_2 extends _i1.SmartFake implements _i4.MemoryService {
  _FakeMemoryService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_3 extends _i1.SmartFake
    implements _i5.NotificationService {
  _FakeNotificationService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_4 extends _i1.SmartFake implements _i6.GeoService {
  _FakeGeoService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_5 extends _i1.SmartFake
    implements _i7.PermissionService {
  _FakePermissionService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_6 extends _i1.SmartFake implements _i8.Client {
  _FakeClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationLocationState_7 extends _i1.SmartFake
    implements _i9.NavigationLocationState {
  _FakeNavigationLocationState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_8 extends _i1.SmartFake implements _i10.File {
  _FakeFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i11.UserController {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isGoogleUser =>
      (super.noSuchMethod(
            Invocation.getter(#isGoogleUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPasswordUser =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i13.Users?> getUserById(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [uid]),
            returnValue: _i12.Future<_i13.Users?>.value(),
            returnValueForMissingStub: _i12.Future<_i13.Users?>.value(),
          )
          as _i12.Future<_i13.Users?>);

  @override
  _i12.Future<List<_i13.Users>> getFollowers(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [uid]),
            returnValue: _i12.Future<List<_i13.Users>>.value(<_i13.Users>[]),
            returnValueForMissingStub: _i12.Future<List<_i13.Users>>.value(
              <_i13.Users>[],
            ),
          )
          as _i12.Future<List<_i13.Users>>);

  @override
  _i12.Future<List<_i13.Users>> getFollowing(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [uid]),
            returnValue: _i12.Future<List<_i13.Users>>.value(<_i13.Users>[]),
            returnValueForMissingStub: _i12.Future<List<_i13.Users>>.value(
              <_i13.Users>[],
            ),
          )
          as _i12.Future<List<_i13.Users>>);

  @override
  _i12.Future<List<String>> getFollowingIds(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingIds, [uid]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<_i13.Users>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i12.Future<List<_i13.Users>>.value(<_i13.Users>[]),
            returnValueForMissingStub: _i12.Future<List<_i13.Users>>.value(
              <_i13.Users>[],
            ),
          )
          as _i12.Future<List<_i13.Users>>);

  @override
  _i12.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateSurname(String? surname) =>
      (super.noSuchMethod(
            Invocation.method(#updateSurname, [surname]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateBirthdate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#updateBirthdate, [date]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateProfilePhoto(_i10.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [image]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [email]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> requestPasswordReset() =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> restoreGoogleProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoogleProfilePhoto, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateUserLevel(String? difficulty) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLevel, [difficulty]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isFollowing(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [targetUid]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> followUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [targetUid]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> unfollowUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [targetUid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  ({String token, String watchId}) extractWatchPair(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#extractWatchPair, [raw]),
            returnValue: (
              token: _i14.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i14.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
            returnValueForMissingStub: (
              token: _i14.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i14.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
          )
          as ({String token, String watchId}));

  @override
  _i12.Future<void> approveWatchPair({
    required String? watchId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveWatchPair, [], {
              #watchId: watchId,
              #token: token,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> changeEmail({
    required String? newEmail,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {
              #newEmail: newEmail,
              #currentPassword: currentPassword,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> refreshEmailFromAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEmailFromAuth, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<Map<String, dynamic>>> getConnectedWatches() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedWatches, []),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<void> enableRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#enableRemoteLogoutForWatch, [watchId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearRemoteLogoutForWatch, [watchId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DiaryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryController extends _i1.Mock implements _i16.DiaryController {
  @override
  List<_i2.Diary> get allDiaries =>
      (super.noSuchMethod(
            Invocation.getter(#allDiaries),
            returnValue: <_i2.Diary>[],
            returnValueForMissingStub: <_i2.Diary>[],
          )
          as List<_i2.Diary>);

  @override
  set currentUser(_i13.Users? user) => super.noSuchMethod(
    Invocation.setter(#currentUser, user),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.Diary updateDiary(
    _i2.Diary? page,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [
              page,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
            ]),
            returnValue: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
            returnValueForMissingStub: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
          )
          as _i2.Diary);

  @override
  _i2.Diary? getDiaryById(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryById, [documentId]),
            returnValueForMissingStub: null,
          )
          as _i2.Diary?);

  @override
  _i12.Future<void> addDiary(
    String? title,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
    bool? modify,
    String? diaryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDiary, [
              title,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
              modify,
              diaryId,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeDiary(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDiary, [diaryId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i2.Diary>?> fetchDiaryById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryById, [userId]),
            returnValue: _i12.Future<List<_i2.Diary>?>.value(),
            returnValueForMissingStub: _i12.Future<List<_i2.Diary>?>.value(),
          )
          as _i12.Future<List<_i2.Diary>?>);

  @override
  _i12.Future<List<String>> uploadDiaryImages(List<_i10.File>? images) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDiaryImages, [images]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<String?> getDownloadUrlChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrlChild, [path]),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<String?> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> deletePhotoFromDb(String? diaryId, String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhotoFromDb, [diaryId, photoPath]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i2.Diary>> getRandomPublicDiariesFromFollowing({
    required List<String>? followingIds,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomPublicDiariesFromFollowing, [], {
              #followingIds: followingIds,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i12.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i12.Future<List<_i2.Diary>>);

  @override
  _i12.Future<List<_i2.Diary>> getPublicDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicDiaries, [userId]),
            returnValue: _i12.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i12.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i12.Future<List<_i2.Diary>>);

  @override
  _i12.Future<List<_i2.Diary>> getPrivateDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateDiaries, [userId]),
            returnValue: _i12.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i12.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i12.Future<List<_i2.Diary>>);

  @override
  _i12.Future<_i2.Diary?> getDiaryByIdAsync(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryByIdAsync, [diaryId]),
            returnValue: _i12.Future<_i2.Diary?>.value(),
            returnValueForMissingStub: _i12.Future<_i2.Diary?>.value(),
          )
          as _i12.Future<_i2.Diary?>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i17.TrekkingController {
  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  _i4.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_2(this, Invocation.getter(#memory)),
            returnValueForMissingStub: _FakeMemoryService_2(
              this,
              Invocation.getter(#memory),
            ),
          )
          as _i4.MemoryService);

  @override
  _i5.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_3(
              this,
              Invocation.getter(#notification),
            ),
            returnValueForMissingStub: _FakeNotificationService_3(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i5.NotificationService);

  @override
  List<_i18.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i18.Trekking>[],
            returnValueForMissingStub: <_i18.Trekking>[],
          )
          as List<_i18.Trekking>);

  @override
  set authService(_i3.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i4.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set notification(_i5.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i18.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i18.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingById, [documentId]),
            returnValueForMissingStub: null,
          )
          as _i18.Trekking?);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingId, [name]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i12.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i12.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
            returnValueForMissingStub: _i12.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<List<_i18.Trekking>> searchTrekking(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrekking, [query]),
            returnValue: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
          )
          as _i12.Future<List<_i18.Trekking>>);

  @override
  _i12.Future<_i18.Trekking?> fetchTrekkingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrekkingById, [id]),
            returnValue: _i12.Future<_i18.Trekking?>.value(),
            returnValueForMissingStub: _i12.Future<_i18.Trekking?>.value(),
          )
          as _i12.Future<_i18.Trekking?>);

  @override
  _i12.Future<List<_i18.Trekking>> getSavedTrekkings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedTrekkings, [uid]),
            returnValue: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
          )
          as _i12.Future<List<_i18.Trekking>>);

  @override
  _i12.Future<void> addTrekkingToSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrekkingToSaved, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeTrekkingFromSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrekkingFromSaved, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isTrekkingSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrekkingSaved, [trekkingId]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i10.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i12.Future<_i10.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i10.File?>.value(),
          )
          as _i12.Future<_i10.File?>);

  @override
  _i12.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i19.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i10.File>> getCachedImages(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImages, [imagePaths]),
            returnValue: _i12.Future<List<_i10.File>>.value(<_i10.File>[]),
            returnValueForMissingStub: _i12.Future<List<_i10.File>>.value(
              <_i10.File>[],
            ),
          )
          as _i12.Future<List<_i10.File>>);

  @override
  _i12.Future<_i18.Trekking?> getTrekkingByIdAsync(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [trekkingId]),
            returnValue: _i12.Future<_i18.Trekking?>.value(),
            returnValueForMissingStub: _i12.Future<_i18.Trekking?>.value(),
          )
          as _i12.Future<_i18.Trekking?>);

  @override
  _i12.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<_i18.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i18.Trekking>>.value(
              <_i18.Trekking>[],
            ),
          )
          as _i12.Future<List<_i18.Trekking>>);

  @override
  _i12.Future<void> updateWeatherNotificationLastCheck() =>
      (super.noSuchMethod(
            Invocation.method(#updateWeatherNotificationLastCheck, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i9.ServiceController {
  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i4.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_2(this, Invocation.getter(#memory)),
            returnValueForMissingStub: _FakeMemoryService_2(
              this,
              Invocation.getter(#memory),
            ),
          )
          as _i4.MemoryService);

  @override
  _i6.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_4(this, Invocation.getter(#geo)),
            returnValueForMissingStub: _FakeGeoService_4(
              this,
              Invocation.getter(#geo),
            ),
          )
          as _i6.GeoService);

  @override
  _i7.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_5(
              this,
              Invocation.getter(#permission),
            ),
            returnValueForMissingStub: _FakePermissionService_5(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i7.PermissionService);

  @override
  _i8.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_6(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_6(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i8.Client);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i4.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i6.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i7.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  String weatherTile(String? layer) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTile, [layer]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
          )
          as String);

  @override
  String? resolveLayer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#resolveLayer, [id]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i12.Future<_i20.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i12.Future<_i20.LatLng?>.value(),
            returnValueForMissingStub: _i12.Future<_i20.LatLng?>.value(),
          )
          as _i12.Future<_i20.LatLng?>);

  @override
  _i12.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang]),
            returnValue: _i12.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i12.Future<Map<String, dynamic>?>.value(),
          )
          as _i12.Future<Map<String, dynamic>?>);

  @override
  _i12.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang]),
            returnValue: _i12.Future<List<Map<String, dynamic>>?>.value(),
            returnValueForMissingStub:
                _i12.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i12.Future<List<Map<String, dynamic>>?>);

  @override
  _i12.Future<bool> hasInternet([
    _i12.Future<List<_i10.InternetAddress>> Function(String)? lookup,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, [lookup]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = true}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i12.Future<List<Map<String, dynamic>>> mockAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, []),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon]),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<_i9.NavigationLocationState> loadNavigationLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadNavigationLocation, []),
            returnValue: _i12.Future<_i9.NavigationLocationState>.value(
              _FakeNavigationLocationState_7(
                this,
                Invocation.method(#loadNavigationLocation, []),
              ),
            ),
            returnValueForMissingStub:
                _i12.Future<_i9.NavigationLocationState>.value(
                  _FakeNavigationLocationState_7(
                    this,
                    Invocation.method(#loadNavigationLocation, []),
                  ),
                ),
          )
          as _i12.Future<_i9.NavigationLocationState>);

  @override
  _i12.Stream<_i21.Position> navigationPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#navigationPositionStream, []),
            returnValue: _i12.Stream<_i21.Position>.empty(),
            returnValueForMissingStub: _i12.Stream<_i21.Position>.empty(),
          )
          as _i12.Stream<_i21.Position>);

  @override
  _i12.Future<void> openGpsSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openGpsSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openPermissionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openPermissionSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  String googleSatelliteTile() =>
      (super.noSuchMethod(
            Invocation.method(#googleSatelliteTile, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
          )
          as String);

  @override
  String weatherTileFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTileFromId, [id]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
          )
          as String);

  @override
  String legendTypeFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#legendTypeFromId, [id]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
          )
          as String);

  @override
  _i12.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i12.Stream<double?>.empty(),
            returnValueForMissingStub: _i12.Stream<double?>.empty(),
          )
          as _i12.Stream<double?>);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i4.MemoryService {
  @override
  _i12.Future<_i10.File?> getImageFromDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromDisk, [url]),
            returnValue: _i12.Future<_i10.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i10.File?>.value(),
          )
          as _i12.Future<_i10.File?>);

  @override
  _i12.Future<_i10.File> cacheImageOnDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImageOnDisk, [url]),
            returnValue: _i12.Future<_i10.File>.value(
              _FakeFile_8(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
            returnValueForMissingStub: _i12.Future<_i10.File>.value(
              _FakeFile_8(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
          )
          as _i12.Future<_i10.File>);

  @override
  _i12.Future<_i10.File?> getImageFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromMemory, [key]),
            returnValue: _i12.Future<_i10.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i10.File?>.value(),
          )
          as _i12.Future<_i10.File?>);

  @override
  void saveImageToMemory(String? key, _i10.File? file) => super.noSuchMethod(
    Invocation.method(#saveImageToMemory, [key, file]),
    returnValueForMissingStub: null,
  );

  @override
  void removeImageFromMemory(String? key) => super.noSuchMethod(
    Invocation.method(#removeImageFromMemory, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<String?> getSavedLocaleCode() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocaleCode, []),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> saveLocaleCode(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocaleCode, [localeCode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Set<String>> getShownWeatherAlertKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getShownWeatherAlertKeys, []),
            returnValue: _i12.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i12.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i12.Future<Set<String>>);

  @override
  _i12.Future<void> saveShownWeatherAlertKeys(Set<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#saveShownWeatherAlertKeys, [keys]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#addShownWeatherAlertKey, [key]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> hasShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasShownWeatherAlertKey, [key]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}
