// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/UserProfilePage/user_page_public_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:triplo/controller/diary.dart' as _i9;
import 'package:triplo/controller/user.dart' as _i3;
import 'package:triplo/model/diary.dart' as _i2;
import 'package:triplo/model/user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiary_0 extends _i1.SmartFake implements _i2.Diary {
  _FakeDiary_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i3.UserController {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isGoogleUser =>
      (super.noSuchMethod(
            Invocation.getter(#isGoogleUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPasswordUser =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadUserCore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserCore, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Users?> getUserById(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [uid]),
            returnValue: _i4.Future<_i5.Users?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Users?>.value(),
          )
          as _i4.Future<_i5.Users?>);

  @override
  _i4.Future<List<_i5.Users>> getFollowers(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [uid]),
            returnValue: _i4.Future<List<_i5.Users>>.value(<_i5.Users>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Users>>.value(
              <_i5.Users>[],
            ),
          )
          as _i4.Future<List<_i5.Users>>);

  @override
  _i4.Future<List<_i5.Users>> getFollowing(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [uid]),
            returnValue: _i4.Future<List<_i5.Users>>.value(<_i5.Users>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Users>>.value(
              <_i5.Users>[],
            ),
          )
          as _i4.Future<List<_i5.Users>>);

  @override
  _i4.Future<List<String>> getFollowingIds(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingIds, [uid]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i5.Users>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i4.Future<List<_i5.Users>>.value(<_i5.Users>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Users>>.value(
              <_i5.Users>[],
            ),
          )
          as _i4.Future<List<_i5.Users>>);

  @override
  _i4.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSurname(String? surname) =>
      (super.noSuchMethod(
            Invocation.method(#updateSurname, [surname]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBirthdate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#updateBirthdate, [date]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfilePhoto(_i6.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [image]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestPasswordReset() =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> restoreGoogleProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#restoreGoogleProfilePhoto, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserLevel(String? difficulty) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLevel, [difficulty]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isFollowing(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [targetUid]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> followUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [targetUid]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> unfollowUser(String? targetUid) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [targetUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  ({String token, String watchId}) extractWatchPair(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#extractWatchPair, [raw]),
            returnValue: (
              token: _i7.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i7.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
            returnValueForMissingStub: (
              token: _i7.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
              watchId: _i7.dummyValue<String>(
                this,
                Invocation.method(#extractWatchPair, [raw]),
              ),
            ),
          )
          as ({String token, String watchId}));

  @override
  _i4.Future<void> approveWatchPair({
    required String? watchId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveWatchPair, [], {
              #watchId: watchId,
              #token: token,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changeEmail({
    required String? newEmail,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {
              #newEmail: newEmail,
              #currentPassword: currentPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshEmailFromAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEmailFromAuth, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getConnectedWatches() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedWatches, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> enableRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#enableRemoteLogoutForWatch, [watchId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearRemoteLogoutForWatch(String? watchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearRemoteLogoutForWatch, [watchId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DiaryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryController extends _i1.Mock implements _i9.DiaryController {
  @override
  List<_i2.Diary> get allDiaries =>
      (super.noSuchMethod(
            Invocation.getter(#allDiaries),
            returnValue: <_i2.Diary>[],
            returnValueForMissingStub: <_i2.Diary>[],
          )
          as List<_i2.Diary>);

  @override
  set currentUser(_i5.Users? user) => super.noSuchMethod(
    Invocation.setter(#currentUser, user),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.Diary updateDiary(
    _i2.Diary? page,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [
              page,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
            ]),
            returnValue: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
            returnValueForMissingStub: _FakeDiary_0(
              this,
              Invocation.method(#updateDiary, [
                page,
                isPublic,
                date,
                duration,
                friends,
                photos,
                challenges,
                refreshmentPoint,
                mood,
                notes,
              ]),
            ),
          )
          as _i2.Diary);

  @override
  _i2.Diary? getDiaryById(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryById, [documentId]),
            returnValueForMissingStub: null,
          )
          as _i2.Diary?);

  @override
  _i4.Future<void> addDiary(
    String? title,
    bool? isPublic,
    String? date,
    double? duration,
    List<String>? friends,
    List<String>? photos,
    List<String>? challenges,
    String? refreshmentPoint,
    List<String>? mood,
    String? notes,
    bool? modify,
    String? diaryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDiary, [
              title,
              isPublic,
              date,
              duration,
              friends,
              photos,
              challenges,
              refreshmentPoint,
              mood,
              notes,
              modify,
              diaryId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeDiary(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDiary, [diaryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Diary>?> fetchDiaryById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryById, [userId]),
            returnValue: _i4.Future<List<_i2.Diary>?>.value(),
            returnValueForMissingStub: _i4.Future<List<_i2.Diary>?>.value(),
          )
          as _i4.Future<List<_i2.Diary>?>);

  @override
  _i4.Future<List<String>> uploadDiaryImages(List<_i6.File>? images) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDiaryImages, [images]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String?> getDownloadUrlChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrlChild, [path]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deletePhotoFromDb(String? diaryId, String? photoPath) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhotoFromDb, [diaryId, photoPath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Diary>> getRandomPublicDiariesFromFollowing({
    required List<String>? followingIds,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomPublicDiariesFromFollowing, [], {
              #followingIds: followingIds,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i4.Future<List<_i2.Diary>>);

  @override
  _i4.Future<List<_i2.Diary>> getPublicDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicDiaries, [userId]),
            returnValue: _i4.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i4.Future<List<_i2.Diary>>);

  @override
  _i4.Future<List<_i2.Diary>> getPrivateDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateDiaries, [userId]),
            returnValue: _i4.Future<List<_i2.Diary>>.value(<_i2.Diary>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Diary>>.value(
              <_i2.Diary>[],
            ),
          )
          as _i4.Future<List<_i2.Diary>>);

  @override
  _i4.Future<_i2.Diary?> getDiaryByIdAsync(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryByIdAsync, [diaryId]),
            returnValue: _i4.Future<_i2.Diary?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Diary?>.value(),
          )
          as _i4.Future<_i2.Diary?>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
