// Mocks generated by Mockito 5.4.6 from annotations
// in app_triplo_wearos/test/controller/user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app_triplo_wearos/service/pairing_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PairingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPairingService extends _i1.Mock implements _i2.PairingService {
  MockPairingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get watchId =>
      (super.noSuchMethod(
            Invocation.getter(#watchId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#watchId),
            ),
          )
          as String);

  @override
  bool get pairing =>
      (super.noSuchMethod(Invocation.getter(#pairing), returnValue: false)
          as bool);

  @override
  bool get remoteLogoutActive =>
      (super.noSuchMethod(
            Invocation.getter(#remoteLogoutActive),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasValidPairId =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidPairId),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> startWatchPairing({bool? forceNew = false}) =>
      (super.noSuchMethod(
            Invocation.method(#startWatchPairing, [], {#forceNew: forceNew}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> restoreWatchPairing() =>
      (super.noSuchMethod(
            Invocation.method(#restoreWatchPairing, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> resetPairingOnLogout({bool? regenerateQr = true}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPairingOnLogout, [], {
              #regenerateQr: regenerateQr,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logoutWatch() =>
      (super.noSuchMethod(
            Invocation.method(#logoutWatch, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
