// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/pages/GeoWatchPage/geowatch_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i12;
import 'dart:ui' as _i17;

import 'package:geolocator/geolocator.dart' as _i13;
import 'package:http/http.dart' as _i5;
import 'package:latlong2/latlong.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:triplo/controller/servicecontroller.dart' as _i6;
import 'package:triplo/controller/trekking.dart' as _i14;
import 'package:triplo/l10n/app_localizations.dart' as _i16;
import 'package:triplo/model/trekking.dart' as _i15;
import 'package:triplo/service/authservice.dart' as _i7;
import 'package:triplo/service/geo.dart' as _i3;
import 'package:triplo/service/memory.dart' as _i2;
import 'package:triplo/service/notification.dart' as _i8;
import 'package:triplo/service/permission.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMemoryService_0 extends _i1.SmartFake implements _i2.MemoryService {
  _FakeMemoryService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeoService_1 extends _i1.SmartFake implements _i3.GeoService {
  _FakeGeoService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionService_2 extends _i1.SmartFake
    implements _i4.PermissionService {
  _FakePermissionService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_3 extends _i1.SmartFake implements _i5.Client {
  _FakeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationLocationState_4 extends _i1.SmartFake
    implements _i6.NavigationLocationState {
  _FakeNavigationLocationState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_5 extends _i1.SmartFake implements _i7.AuthService {
  _FakeAuthService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_6 extends _i1.SmartFake
    implements _i8.NotificationService {
  _FakeNotificationService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServiceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceController extends _i1.Mock implements _i6.ServiceController {
  MockServiceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openWeatherKey =>
      (super.noSuchMethod(
            Invocation.getter(#openWeatherKey),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#openWeatherKey),
            ),
          )
          as String);

  @override
  String get weatherbitKey =>
      (super.noSuchMethod(
            Invocation.getter(#weatherbitKey),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#weatherbitKey),
            ),
          )
          as String);

  @override
  _i2.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_0(this, Invocation.getter(#memory)),
          )
          as _i2.MemoryService);

  @override
  _i3.GeoService get geo =>
      (super.noSuchMethod(
            Invocation.getter(#geo),
            returnValue: _FakeGeoService_1(this, Invocation.getter(#geo)),
          )
          as _i3.GeoService);

  @override
  _i4.PermissionService get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _FakePermissionService_2(
              this,
              Invocation.getter(#permission),
            ),
          )
          as _i4.PermissionService);

  @override
  _i5.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_3(this, Invocation.getter(#client)),
          )
          as _i5.Client);

  @override
  set openWeatherKey(String? value) => super.noSuchMethod(
    Invocation.setter(#openWeatherKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set weatherbitKey(String? value) => super.noSuchMethod(
    Invocation.setter(#weatherbitKey, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i2.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set geo(_i3.GeoService? value) => super.noSuchMethod(
    Invocation.setter(#geo, value),
    returnValueForMissingStub: null,
  );

  @override
  set permission(_i4.PermissionService? value) => super.noSuchMethod(
    Invocation.setter(#permission, value),
    returnValueForMissingStub: null,
  );

  @override
  String weatherTile(String? layer) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTile, [layer]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#weatherTile, [layer]),
            ),
          )
          as String);

  @override
  String? resolveLayer(String? id) =>
      (super.noSuchMethod(Invocation.method(#resolveLayer, [id])) as String?);

  @override
  _i10.Future<_i11.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i10.Future<_i11.LatLng?>.value(),
          )
          as _i10.Future<_i11.LatLng?>);

  @override
  _i10.Future<Map<String, dynamic>?> weather(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weather, [lat, lon, lang]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<Map<String, dynamic>>?> forecast(
    double? lat,
    double? lon,
    String? lang,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forecast, [lat, lon, lang]),
            returnValue: _i10.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i10.Future<List<Map<String, dynamic>>?>);

  @override
  _i10.Future<bool> hasInternet([
    _i10.Future<List<_i12.InternetAddress>> Function(String)? lookup,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#hasInternet, [lookup]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  String weatherIconUrl(String? iconCode, {bool? big = true}) =>
      (super.noSuchMethod(
            Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#weatherIconUrl, [iconCode], {#big: big}),
            ),
          )
          as String);

  @override
  Map<String, dynamic> parseForecastItem(Map<String, dynamic>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecastItem, [raw]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> parseForecast(List<Map<String, dynamic>>? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseForecast, [raw]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String openTopoMapTile() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapTile, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#openTopoMapTile, []),
            ),
          )
          as String);

  @override
  List<String> openTopoMapSubdomains() =>
      (super.noSuchMethod(
            Invocation.method(#openTopoMapSubdomains, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i10.Future<List<Map<String, dynamic>>> mockAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#mockAlerts, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> weatherbitAlerts(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#weatherbitAlerts, [lat, lon]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<_i6.NavigationLocationState> loadNavigationLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadNavigationLocation, []),
            returnValue: _i10.Future<_i6.NavigationLocationState>.value(
              _FakeNavigationLocationState_4(
                this,
                Invocation.method(#loadNavigationLocation, []),
              ),
            ),
          )
          as _i10.Future<_i6.NavigationLocationState>);

  @override
  _i10.Stream<_i13.Position> navigationPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#navigationPositionStream, []),
            returnValue: _i10.Stream<_i13.Position>.empty(),
          )
          as _i10.Stream<_i13.Position>);

  @override
  _i10.Future<void> openGpsSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openGpsSettings, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> openPermissionSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openPermissionSettings, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  String googleSatelliteTile() =>
      (super.noSuchMethod(
            Invocation.method(#googleSatelliteTile, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#googleSatelliteTile, []),
            ),
          )
          as String);

  @override
  String weatherTileFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#weatherTileFromId, [id]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#weatherTileFromId, [id]),
            ),
          )
          as String);

  @override
  String legendTypeFromId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#legendTypeFromId, [id]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#legendTypeFromId, [id]),
            ),
          )
          as String);

  @override
  _i10.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i10.Stream<double?>.empty(),
          )
          as _i10.Stream<double?>);
}

/// A class which mocks [TrekkingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrekkingController extends _i1.Mock
    implements _i14.TrekkingController {
  MockTrekkingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_5(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i7.AuthService);

  @override
  _i2.MemoryService get memory =>
      (super.noSuchMethod(
            Invocation.getter(#memory),
            returnValue: _FakeMemoryService_0(this, Invocation.getter(#memory)),
          )
          as _i2.MemoryService);

  @override
  _i8.NotificationService get notification =>
      (super.noSuchMethod(
            Invocation.getter(#notification),
            returnValue: _FakeNotificationService_6(
              this,
              Invocation.getter(#notification),
            ),
          )
          as _i8.NotificationService);

  @override
  List<_i15.Trekking> get allTrekkings =>
      (super.noSuchMethod(
            Invocation.getter(#allTrekkings),
            returnValue: <_i15.Trekking>[],
          )
          as List<_i15.Trekking>);

  @override
  set authService(_i7.AuthService? value) => super.noSuchMethod(
    Invocation.setter(#authService, value),
    returnValueForMissingStub: null,
  );

  @override
  set memory(_i2.MemoryService? value) => super.noSuchMethod(
    Invocation.setter(#memory, value),
    returnValueForMissingStub: null,
  );

  @override
  set notification(_i8.NotificationService? value) => super.noSuchMethod(
    Invocation.setter(#notification, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrekkingSelected(void Function(_i15.Trekking)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrekkingSelected, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> loadTrekking() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrekking, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i15.Trekking? getTrekkingById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingById, [documentId]))
          as _i15.Trekking?);

  @override
  String? getTrekkingId(String? name) =>
      (super.noSuchMethod(Invocation.method(#getTrekkingId, [name]))
          as String?);

  @override
  _i10.Future<List<String>> getDownloadUrls(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrls, [paths]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<String> getDownloadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [path]),
            returnValue: _i10.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getDownloadUrl, [path]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<List<_i15.Trekking>> searchTrekking(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrekking, [query]),
            returnValue: _i10.Future<List<_i15.Trekking>>.value(
              <_i15.Trekking>[],
            ),
          )
          as _i10.Future<List<_i15.Trekking>>);

  @override
  _i10.Future<_i15.Trekking?> fetchTrekkingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrekkingById, [id]),
            returnValue: _i10.Future<_i15.Trekking?>.value(),
          )
          as _i10.Future<_i15.Trekking?>);

  @override
  _i10.Future<List<_i15.Trekking>> getSavedTrekkings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedTrekkings, [uid]),
            returnValue: _i10.Future<List<_i15.Trekking>>.value(
              <_i15.Trekking>[],
            ),
          )
          as _i10.Future<List<_i15.Trekking>>);

  @override
  _i10.Future<void> addTrekkingToSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrekkingToSaved, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeTrekkingFromSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrekkingFromSaved, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> isTrekkingSaved(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrekkingSaved, [trekkingId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i12.File?> getCachedImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, [imagePath]),
            returnValue: _i10.Future<_i12.File?>.value(),
          )
          as _i10.Future<_i12.File?>);

  @override
  _i10.Future<void> checkArrival(
    String? trekkingId,
    double? distanceInMeters,
    _i16.AppLocalizations? local,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkArrival, [
              trekkingId,
              distanceInMeters,
              local,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i12.File>> getCachedImages(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImages, [imagePaths]),
            returnValue: _i10.Future<List<_i12.File>>.value(<_i12.File>[]),
          )
          as _i10.Future<List<_i12.File>>);

  @override
  _i10.Future<_i15.Trekking?> getTrekkingByIdAsync(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrekkingByIdAsync, [trekkingId]),
            returnValue: _i10.Future<_i15.Trekking?>.value(),
          )
          as _i10.Future<_i15.Trekking?>);

  @override
  _i10.Future<void> enableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#enableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> disableWeatherAlertForTrekking(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#disableWeatherAlertForTrekking, [trekkingId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> isWeatherAlertEnabled(String? trekkingId) =>
      (super.noSuchMethod(
            Invocation.method(#isWeatherAlertEnabled, [trekkingId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<String>> getWeatherAlertTrekkingIds() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkingIds, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<List<_i15.Trekking>> getWeatherAlertTrekkings() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherAlertTrekkings, []),
            returnValue: _i10.Future<List<_i15.Trekking>>.value(
              <_i15.Trekking>[],
            ),
          )
          as _i10.Future<List<_i15.Trekking>>);

  @override
  _i10.Future<void> updateWeatherNotificationLastCheck() =>
      (super.noSuchMethod(
            Invocation.method(#updateWeatherNotificationLastCheck, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
