// Mocks generated by Mockito 5.4.6 from annotations
// in triplo/test/controller/servicecontroller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:geolocator/geolocator.dart' as _i7;
import 'package:latlong2/latlong.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i9;
import 'package:triplo/service/geo.dart' as _i5;
import 'package:triplo/service/memory.dart' as _i3;
import 'package:triplo/service/permission.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i3.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.File?> getImageFromDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromDisk, [url]),
            returnValue: _i4.Future<_i2.File?>.value(),
          )
          as _i4.Future<_i2.File?>);

  @override
  _i4.Future<_i2.File> cacheImageOnDisk(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImageOnDisk, [url]),
            returnValue: _i4.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#cacheImageOnDisk, [url])),
            ),
          )
          as _i4.Future<_i2.File>);

  @override
  _i4.Future<_i2.File?> getImageFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFromMemory, [key]),
            returnValue: _i4.Future<_i2.File?>.value(),
          )
          as _i4.Future<_i2.File?>);

  @override
  void saveImageToMemory(String? key, _i2.File? file) => super.noSuchMethod(
    Invocation.method(#saveImageToMemory, [key, file]),
    returnValueForMissingStub: null,
  );

  @override
  void removeImageFromMemory(String? key) => super.noSuchMethod(
    Invocation.method(#removeImageFromMemory, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryCache() => super.noSuchMethod(
    Invocation.method(#clearMemoryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> getSavedLocaleCode() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocaleCode, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveLocaleCode(String? localeCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocaleCode, [localeCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Set<String>> getShownWeatherAlertKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getShownWeatherAlertKeys, []),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> saveShownWeatherAlertKeys(Set<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#saveShownWeatherAlertKeys, [keys]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#addShownWeatherAlertKey, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasShownWeatherAlertKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasShownWeatherAlertKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [GeoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoService extends _i1.Mock implements _i5.GeoService {
  MockGeoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.LatLng?> userLocation() =>
      (super.noSuchMethod(
            Invocation.method(#userLocation, []),
            returnValue: _i4.Future<_i6.LatLng?>.value(),
          )
          as _i4.Future<_i6.LatLng?>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i7.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i4.Stream<_i7.Position>.empty(),
          )
          as _i4.Stream<_i7.Position>);

  @override
  _i4.Future<bool> openLocationSettingsPage() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettingsPage, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<double?> compassStream() =>
      (super.noSuchMethod(
            Invocation.method(#compassStream, []),
            returnValue: _i4.Stream<double?>.empty(),
          )
          as _i4.Stream<double?>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i8.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> askPermissionsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#askPermissionsOnce, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.PermissionStatus> locationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#locationStatus, []),
            returnValue: _i4.Future<_i9.PermissionStatus>.value(
              _i9.PermissionStatus.denied,
            ),
          )
          as _i4.Future<_i9.PermissionStatus>);

  @override
  _i4.Future<bool> isLocationGranted() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationGranted, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isLocationDenied() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationDenied, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> openAppSettingsPage() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettingsPage, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
